### ISSUE TITLE
Prevent confusion with the commercial plugin

### ISSUE THREAD

**Issue by Stephan202** [Backelite/sonar-swift#1]
I just dropped `sonar-swift-plugin-0.1.jar` into our SonarQube 5.2 installation. It's recognized just fine, quality profiles and rules and all, which is nice :). (Can't give feedback on analysis results yet; I'm not involved in Swift development in our company, and I haven't communicated yet that I installed this plugin.)

But when I go to the Update Center, it suggests that I upgrade the plugin from version 0.1 to 1.5, with a link to the home page and release notes of the [commercially available/official Swift plugin](http://www.sonarsource.com/products/plugins/languages/swift/). That's quite confusing, and probably not what you want. :)

**Comment by zippy1978** [comment]
Thank you @Stephan202 !

I forgot to check that... 
I will fix it in the next release.

Gilles

**Comment by giacgbj** [comment]
:+1:

**Comment by giacgbj** [comment]
Is there a reason you don't close this ticket?
It's the fourth release after the "next release".

It's not only a matter of confusion regarding the aforementioned information: if you automatically update your plugin, the downloaded file is actually https://sonarsource.bintray.com/CommercialDistribution/sonar-swift/sonar-swift-plugin-1.5.1.jar (from http://www.sonarsource.com/products/plugins/languages/swift/). 

The result is that you wipe out your plugin and install the commercial one! :-)

**Comment by zippy1978** [comment]
Hi
I know... But I did not manage to find on which id/property of the plugin the Update Center relies on yet...

**Comment by rompic** [comment]
https://github.com/octo-technology/sonar-objective-c/issues/88

There was a similar Problem with sonar objective-c

**Comment by zippy1978** [comment]
Ok,

So, I just need to change the language key and few other things.
But I don't know what key to use yet.... "swift" was good :), anything else will not be as readable / understandable...

Your ideas are welcomed !

**Comment by rompic** [comment]
swift-ce ?

**Comment by gretzki** [comment]
swiftos (for open source),
swifty,
swifflemanizzle

You're welcome! ;P

**Comment by zippy1978** [comment]
Hi,

I changed everything as detailed in PR https://github.com/octo-technology/sonar-objective-c/issues/88.

But still the confusion remains in the update center....

Any ideas ?

**Comment by zippy1978** [comment]
Finally fixed !
And I did not have to change language key.

It is available in release 0.2.2
