### ISSUE TITLE
No lint reports generated using 0.3.5

### ISSUE THREAD

**Issue by luowei428** [Backelite/sonar-swift#101]
Hello, 

I have read issue #90 and #47 .
I run tests using:
SonarQube 6.5 & backelite-sonar-swift-plugin-0.3.5.jar.
And I can see that swiftlint finished. but there is no lint reports and 0 Bugs & Vulnerabilities.
Any suggestion would be appreciated.

![screen shot 2017-09-14 at 4 41 53 pm](https://user-images.githubusercontent.com/11496301/30415647-47633f54-996c-11e7-8fb3-4c6d968aa6fb.png)

![screen shot 2017-09-14 at 4 46 23 pm](https://user-images.githubusercontent.com/11496301/30415650-4e301c6c-996c-11e7-9b08-80c2eaaa8053.png)

**Comment by luowei428** [comment]
Did anyone try this plugin with SonarQube 6.5?  Does it work well?
Thanks a lot!

**Comment by sherifkozman** [comment]
No same thing, i thought i had an issue with my deployment but apparently its common with 6.5 i have removed the entire plugin and tried SonarSwift with a demo key and results were populated normally.

**Comment by luowei428** [comment]
@sherifkozman how about SonarQube 5.X? Did you try that? I have a problem of starting SonarQube 5.6.6 currently.

**Comment by sherifkozman** [comment]
@luowei428 no i havent tested 5.X as our production is on 6.5 which is why we test over a similar version but this may be related to the latest plugin fix from 0.3.4 to 0.3.5

**Comment by luowei428** [comment]
Hi,
All who concern this issue, I think that the swiftlint report is generated and uploaded to SonarQube. The problem is that SonarQube treats all issues as Code Smells rather than bugs or vulnerabilities.
After changing an issue's type to bugs, the number of bugs becomes to 1. So I guess I missed a kind of config files to define rules of this plugin.
As I correct? What's your thoughts?
![screen shot 2017-09-19 at 10 23 00 am](https://user-images.githubusercontent.com/11496301/30570419-8f3381ca-9d24-11e7-9af9-a61d395237e4.png)

**Comment by sherifkozman** [comment]
I do believe its an issue that occurred after the latest plugin update which is why all errors generated goes onto code smell rather than bugs

**Comment by luowei428** [comment]
Yes, I agree. All the rules' types are Code Smell. Maybe something wrong with rules config.
@pbernery  @zippy1978

**Comment by pbernery** [comment]
Hello,

Indeed, all issues are reported as Code Smells as of now. Code Smells vs Bugs/Vulnerabilities have been introduced in [SonarQube 5.5](https://blog.sonarsource.com/bugs-and-vulnerabilities-are-1st-class-citizens-in-sonarqube-quality-model-along-with-code-smells/).
The Swift plugin has not been updated yet to differentiate code smells, bugs and vulnerabilities.

**Comment by luowei428** [comment]
Thanks for your update!
Looking forward to new version.

**Comment by devashree-shukla** [comment]
Any solution for this ??

**Comment by benMohamed** [comment]
Same problem, Any solution please ??

**Comment by aelam** [comment]
Why is it closed

**Comment by zouinetami** [comment]
hey, i have "**backelite-sonar-swift-plugin-0.4.6**" version and i still have same problem.

**Comment by devashree-shukla** [comment]
You need to have commercial version
