### ISSUE TITLE
Contribution request: Gradle

### ISSUE THREAD

**Issue by vexdev** [Backelite/sonar-swift#104]
Are you willing to evaluate a PR which brings gradle as build system?

As you know, It has various advantages over maven, but the most important point here I think is the fact that the gradlew wrapper is shipped with the source, so it does not need the building server to have any extra software installed.

I've got a PR ready if you like.

**Comment by vexdev** [comment]
I opened the PR for review: #106

**Comment by zippy1978** [comment]
Thanks @vexdev !
I will have a look.
As sonar is using Maven artifacts for plugin development, I fear maintaining a Gradle script aside will generate more maintenance....
