### ISSUE TITLE
Is it possible to use sonar-swift, with SonarQube installed on Windows server?

### ISSUE THREAD

**Issue by marccals** [Backelite/sonar-swift#107]
Hello,

In our company there is a team building iOS applications. We want to perform code static analysis on 
swift code. We are considering to use your plugin.

Reading documentation it's not clear if our current SonarQube configuration will work with this plugin. The code analysis where is performed in SonarQube server or in developer machine/continuous integration machine?

Let me explain. Our SonarQube instance is running on Windows Server. Looking at your documentation it's explained for Linux and Mac. Will it work for us if our SonarQube Server is a windows? It seems that is needed some tools like xcpretty that will not work in Windows. Have this tools been installed in SonarQube server or in the machine that perform analysis? Will work this plugin if our SonarQube server is a Windows Server?

Thanks

**Comment by vishnuvpotti** [comment]
I am not an expert, but can tell from my experience using sonarqube from past few months.
You can have Sonarqube server running in a windows machine. All the prerequisites like xcpretty needs to be installed on mac (on agent machine).
Having said that, I am also trying to get analysis done for swift projects. 
Hope this helps.

**Comment by marccals** [comment]
Thanks @vishnuvpotti , I tried and it works perfectly. As you said all the prerequisites are only needed on mac agent.

**Comment by babusatti** [comment]
is this plugin works in linux platform? @marccals @vishnuvpotti 
i am getting 'metric' issue below.

ERROR: Error during SonarScanner execution
java.lang.UnsupportedOperationException: Metric 'files' should not be computed by a Sensor
at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:173)
at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:137)
at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:96)
at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
at org.sonar.plugins.gosu.GosuSensor.saveMetric(GosuSensor.java:254)

**Comment by marccals** [comment]
Hello @babusatti ,

I don't know it , we ran the plugin in a Mac computer. We didn't try with Linux one.
