### ISSUE TITLE
Duplication percentage is not showing up in SonarQube 6.7

### ISSUE THREAD

**Issue by singh88** [Backelite/sonar-swift#114]
Duplication percentage is not showing up in SonarQube 6.7 but its working fine in 6.5
<img width="880" alt="screen shot 2017-12-13 at 1 12 37 pm" src="https://user-images.githubusercontent.com/5465858/33962752-68f7ab00-e007-11e7-9fd4-c84a202f45d9.png">

What part of the plugin code generates that?

**Comment by singh88** [comment]
<img width="880" alt="screen shot 2017-12-13 at 1 12 37 pm" src="https://user-images.githubusercontent.com/5465858/33962752-68f7ab00-e007-11e7-9fd4-c84a202f45d9.png">

**Comment by Mindbowser** [comment]
@singh88 any luck?

**Comment by singh88** [comment]
Nope!!

**Comment by singh88** [comment]
Closing this issue since it works fine.

**Comment by samuel-gallet** [comment]
@singh88 did you find a solution?
I got the same issue while upgrading to SonarQube 6.7.

**Comment by salmojunior** [comment]
The issue still

**Comment by cah-iswaria-sasi** [comment]
why duplication block alone not showing any data?
