### ISSUE TITLE
Linux installation guide?

### ISSUE THREAD

**Issue by oookotooo** [Backelite/sonar-swift#115]
Hello,

I have installed a plugin to sonarqube plugins directory.

SonarQube sees plugin, but seems not working

![mfa_ios - google chrome](https://user-images.githubusercontent.com/15310858/34943719-7991675e-fa05-11e7-9469-1186830af450.jpg)

Any guide how to use it in linux?

**Comment by americoneto1** [comment]
+1

**Comment by HankQuiter** [comment]
Not totally sure here, not a whole lot of info, but I am pretty sure; you need to have at least the sonar scanner and xcode on an apple computer/device

**Comment by zippy1978** [comment]
Hi @oookotooo,

Did you try to set Tailor as default Quality profile ?

**Comment by oookotooo** [comment]
@zippy1978, I'm not sure, but as I remember I did that.

**Comment by gaelfoppolo** [comment]
Do you still face this issue?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
