### ISSUE TITLE
fastlane plugin for lizard

### ISSUE THREAD

**Issue by liaogz82** [Backelite/sonar-swift#116]
Hi, I am giving a shoutout for the fastlane lizard plugin that i have created.

https://github.com/liaogz82/fastlane-plugin-lizard

https://rubygems.org/gems/fastlane-plugin-lizard

Please check this out. Thanks!

**Comment by singh88** [comment]
Great Job!!

**Comment by singh88** [comment]
Is there any plan on getting this into fastlane official build system.

**Comment by liaogz82** [comment]
yes there is. The quickness will depend how popular lizard is

In the meantime, please fork out the repo and help me check the code out.
