### ISSUE TITLE
run-sonar-swift.sh doesn't parse workspace and xcode project names with spaces properly

### ISSUE THREAD

**Issue by HankQuiter** [Backelite/sonar-swift#120]
not sure who owns  **run-sonar-swift.sh**  cannot find it in a repo that I think is the owners
but the following issue exists.

If you set the following properties in the sonar-project.properties as follows:
sonar.swift.project=firstWord secondWord.xcodeproj
sonar.swift.workspace=firstWord secondWord.xcworkspace
you will get an error (at least on MAC osx) about how the work space name 'secondWord.xcworkspace' is not valid or not found or something. as you can see it doesn't include the whole property just the last part after the space.
I found that i if you edit lines 264 and 266 
**from** 
264 buildCmd+=(-workspace $workspaceFile)
...
266 buildCmd+=(-project $projectFile)

**to**
264 buildCmd+=(-workspace "$workspaceFile")
...
266 buildCmd+=(-project "$projectFile")

the parsing of the properties works properly with spaces in the directory/file names

**Comment by m1entus** [comment]
Same issue here

**Comment by komalguptatii** [comment]
Any solutions to this?

**Comment by HankQuiter** [comment]
> Any solutions to this?

The solution is in the explanation:
```
I found that i if you edit lines 264 and 266
from
264 buildCmd+=(-workspace $workspaceFile)
...
266 buildCmd+=(-project $projectFile)

to
264 buildCmd+=(-workspace "$workspaceFile")
...
266 buildCmd+=(-project "$projectFile")
```

**Comment by gaelfoppolo** [comment]
https://github.com/Backelite/sonar-swift/pull/234 should fix this issue. Awaiting merge.
