### ISSUE TITLE
Supporting OWASP Standards

### ISSUE THREAD

**Issue by fisherv1** [Backelite/sonar-swift#126]
Hi Team,

For this sonar-swift plugin, is it supporting OWASP standards? 

Please see this link:https://www.sonarsource.com/products/codeanalyzers/sonarswift.html

Just want to find out this plugin is supporting OWASP or not? Thanks

**Comment by zippy1978** [comment]
Hi @fisherv1,

No it does not.
For analysis the plugin relies on SwiftLint and Tailor (for Linux).
