### ISSUE TITLE
LizardMeasurePersistor can't find index project file referenced in lizard report

### ISSUE THREAD

**Issue by gretzki** [Backelite/sonar-swift#13]
The lizard report is not processed although the report is successfully found.
The method
```
if (fileExists(sensorContext, file))
```
in LizardMeasurePersistor.java fails if the resources is allocated by using 
```
fileSystem.baseDir().
```
When this is left out, the parsing succeeds successfully.
This approach has been tested and can be reviewed in the following PR: https://github.com/Backelite/sonar-swift/pull/12

Cheers,
Chris

**Comment by zippy1978** [comment]
Thank you.

It is merged on develop and will be released soon.
