### ISSUE TITLE
Error on saving results of complexity analysis

### ISSUE THREAD

**Issue by edopelawi** [Backelite/sonar-swift#136]
Setup:

SonarQube Scanner 3.1.0.1141
Java 10.0.1 Oracle Corporation (64-bit)
Mac OS X 10.13.4 x86_64
SonarQube server 7.1.0

Lizard 1.14.10
Tailor 0.12.0
SwiftLint 0.24.0

Since the version 0.3.5 doesn't support 7.1.0, I checked out from develop branch (`0c48009`) and ran `build-and-deploy.sh` manually. 

Nothing really stands out from the `sonar-project.properties`, I used the basic setup. The project has unit test files.

Issue:

When I ran `run-sonar-swift.sh`, it shows error (or exception?) like the ones in issue #75. After trying to dig down the code, it seems the issue was on the `LizardMeasurePersistor.java`'s code. It seems to throw exception on the line 69. 

When I tried to include the exception on the log, it shows the same issue like #75: `java.lang.UnsupportedOperationException: Metric 'function_complexity' should not be computed by a Sensor`.

Of course, the reports still shows up in the SonarQube dashboard, but it doesn't include Lizard's result.

Thanks in advance!

**Comment by gaelfoppolo** [comment]
Do you still face this issue on the current version of the plugin?
Can you provide a project sample to reproduce the issue?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
