### ISSUE TITLE
Problem with Bugs and Vulnerabilities in Qube

### ISSUE THREAD

**Issue by caioschristino** [Backelite/sonar-swift#139]
I'm using the Backelite / sonar-swift to show metrics of my code but when I send the result to sonarqube but, the dashboard does not show the Bugs and Vulnerabilities. All process (Swiftlint, Taylor, Lizard ..) are executed.

Someone can help me?
![sonarqube](https://user-images.githubusercontent.com/15656147/40062509-c3debf34-5831-11e8-99ed-6a36cbfdbf79.png)

**Comment by radimhalfar** [comment]
We've got the same problem here. What is the latest stable version for plugin & sonarqube server.

**Comment by singh88** [comment]
its because all the rules under swiftlint are defined as a code smell.

**Comment by Canvass** [comment]
I've the same problem. Have you got any solution?

**Comment by soufianeEssabbane** [comment]
still the same problem no Bugs/Vulnerabilities :s

**Comment by soufianeEssabbane** [comment]
@caioschristino were you able to find a solution ?

**Comment by costaneto222** [comment]
> its because all the rules under swiftlint are defined as a code smell.

@singh88, I don't get it. We have to create this rules?
Can you make a sample to us? How we defined a rule as a vulnerability instead code smell?

**Comment by ViniciusGibran** [comment]
Same problem here! We're using Lizard & SwiftLint rules as our project has no tests yet, but it gives code smells only.. We appreciate any help. Thank you!

**Comment by gaelfoppolo** [comment]
Duplicate of #101. Closing this one.
