### ISSUE TITLE
The latest sonar scanner 2.5 will not import issues from swiftlint.

### ISSUE THREAD

**Issue by deanml** [Backelite/sonar-swift#14]
I am using the latest sonarqube scanner version 2.5 and sonarqube server v. 5.1.2 with SwiftLint Version 0.8.0.  The run-sonar-swift.sh file executes successfully as does the latest sonarqube scanner if I run it manually outside the run-sonar-swift.sh script.  The sonar-reports folder does contain several *swiftlint.txt files generated during the run.  Some of them are empty but most of them are not.  During the sonarqube scanner execution I do see:

08:46:05.179 INFO - Sensor org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor@7836f56
08:46:05.180 INFO - Processing SwiftLint report sonar-reports/AncestryShareExtension-swiftlint.txt
08:46:05.180 INFO - Processing SwiftLint report sonar-reports/AncestryTodayExtension-swiftlint.txt
08:46:05.180 INFO - Processing SwiftLint report sonar-reports/AncestryViews-swiftlint.txt
08:46:05.204 INFO - Processing SwiftLint report sonar-reports/AncestryWatchKitApp-swiftlint.txt
08:46:05.204 INFO - Processing SwiftLint report sonar-reports/AncestryWatchkitExtension-swiftlint.txt
08:46:05.324 INFO - Processing SwiftLint report sonar-reports/AppIcon-swiftlint.txt
08:46:05.324 INFO - Processing SwiftLint report sonar-reports/Classes-swiftlint.txt
08:46:05.324 INFO - Processing SwiftLint report sonar-reports/Frameworks-swiftlint.txt
08:46:05.372 INFO - Processing SwiftLint report sonar-reports/Resources-swiftlint.txt
08:46:05.372 INFO - Processing SwiftLint report sonar-reports/Source-swiftlint.txt
08:46:05.690 INFO - Processing SwiftLint report sonar-reports/TDDProjects-swiftlint.txt
08:46:05.691 INFO - Processing SwiftLint report sonar-reports/Utilities-swiftlint.txt
08:46:05.692 INFO - Sensor org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor@7836f56 (done) | time=513ms

However no issues are imported into the sonar project on the sonar server.  No other information is available in the sonarqube scanner output even if I use the -X option.  I've triple checked My sonar-project.properties file and have all the required parameters set including 
sonar.swift.swiftlint.report=sonar-reports/\*swiftlint.txt
sonar.swift.excludedPathsFromCoverage=.\*Tests.\*

These are the files located in my sonar-reports folder:
-rw-r--r--   1 iosbuilds  staff         0 Mar  2 15:51 AncestryShareExtension-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff         0 Mar  2 15:51 AncestryTodayExtension-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff     54765 Mar  2 15:51 AncestryViews-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff         0 Mar  2 15:51 AncestryWatchKitApp-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff    472241 Mar  2 15:51 AncestryWatchkitExtension-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff         0 Mar  2 15:51 AppIcon-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff         0 Mar  2 15:51 Classes-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff    223251 Mar  2 15:51 Frameworks-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff         0 Mar  2 15:51 Resources-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff   2185338 Mar  2 15:51 Source-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff     17382 Mar  2 15:51 TDDProjects-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff       101 Mar  2 15:49 TEST-report.xml
-rw-r--r--   1 iosbuilds  staff         0 Mar  2 15:51 Utilities-swiftlint.txt
-rw-r--r--   1 iosbuilds  staff       165 Mar  2 15:49 coverage.xml
-rw-r--r--   1 iosbuilds  staff  22533303 Mar  2 15:51 xcodebuild.log

In all honesty I do not know if this is related to the latest sonarqube scanner but will backrev and do some more experimentation and update as appropriate.

**Comment by deanml** [comment]
I removed the sonar.swift.swiftlint.report line in the sonar-project.properties and it now states during the sonar scanner run:
08:46:05.179 INFO  - Sensor org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor@7836f566
08:46:05.180 INFO  - Processing SwiftLint report sonar-reports/AncestryShareExtension-swiftlint.txt
08:46:05.180 INFO  - Processing SwiftLint report sonar-reports/AncestryTodayExtension-swiftlint.txt
08:46:05.180 INFO  - Processing SwiftLint report sonar-reports/AncestryViews-swiftlint.txt
08:46:05.204 INFO  - Processing SwiftLint report sonar-reports/AncestryWatchKitApp-swiftlint.txt
08:46:05.204 INFO  - Processing SwiftLint report sonar-reports/AncestryWatchkitExtension-swiftlint.txt
08:46:05.324 INFO  - Processing SwiftLint report sonar-reports/AppIcon-swiftlint.txt
08:46:05.324 INFO  - Processing SwiftLint report sonar-reports/Classes-swiftlint.txt
08:46:05.324 INFO  - Processing SwiftLint report sonar-reports/Frameworks-swiftlint.txt
08:46:05.372 INFO  - Processing SwiftLint report sonar-reports/Resources-swiftlint.txt
08:46:05.372 INFO  - Processing SwiftLint report sonar-reports/Source-swiftlint.txt
08:46:05.690 INFO  - Processing SwiftLint report sonar-reports/TDDProjects-swiftlint.txt
08:46:05.691 INFO  - Processing SwiftLint report sonar-reports/Utilities-swiftlint.txt
08:46:05.692 INFO  - Sensor org.sonar.plugins.swift.issues.swiftlint.SwiftLintSensor@7836f566 (done) | time=513ms

But still no issues in Sonarqube are showing up.

**Comment by electricsunny** [comment]
I'm having the same issue.  MyApp-swiftlint.txt is being created, with the following contents, but the results are not visible in sonar.
Sonar 5.1.2
Sonar Runner 2.4

MyApp-swiftlint.txt

Linting Swift files at path MyApp
Linting 'AppDelegate.swift' (1/4)
Linting 'ViewController.swift' (2/4)
Linting 'AppDelegate.swift' (3/4)
Linting 'ViewController.swift' (4/4)
Done linting! Found 20 violations, 4 serious in 4 files.

**Comment by electricsunny** [comment]
Apologies - the issue I was seeing above was caused by an incorrect version of SwiftLint, I was stuck on 0.2.0, should have been at least 0.3.0.

**Comment by deanml** [comment]
elicsunny's problem is not my problem I still think there is a bug here.

**Comment by venkatchm** [comment]
Im also facing the same issue. In log, its shows issues but that not shown up in server. My swiftlint version is 0.9.1.
