### ISSUE TITLE
Xcode 9.4 Code Coverage Report format is not Supported by Slather and Sonar-Swift

### ISSUE THREAD

**Issue by singh88** [Backelite/sonar-swift#146]
From Xcode 9.4, Apple has made changes to its output file format for code coverage and it's not `.xccoverage` any more which is failing slather to generate code coverage report. This results in no code coverage information on SonarQube dashboard.

https://github.com/SlatherOrg/slather/issues/401

**Comment by kapfab** [comment]
We have Xcode 9.4 installed on our CI platform and we still have our code coverage updated in Sonar (we use Slather via Fastlane)

**Comment by singh88** [comment]
@kapfab do you mind double checking this for me because I am sure that this new `Xcode 9.4` configurations are breaking Slather code coverage parsing.

**Comment by kapfab** [comment]
@singh88, I confirm we use Xcode 9.4 and we have code coverage in Sonar.
Though, as pointed by @kenji21 in your Slather issue, having a project in Xcode 8.0 compatible format could be an explanation of why it still works…

**Comment by kapfab** [comment]
After several tests, Slather seems to work fine with Xcode 9.4, be it with old project or whole new projects created with Xcode 9.4.1.

**Comment by antoine20001** [comment]
Works with Xcode 10, slather 2.4.6, sonar-swift 0.4.3

**Comment by gaelfoppolo** [comment]
You need to declare your project `Xcode 8.0-compatible`.
![](https://user-images.githubusercontent.com/1105089/42054757-85475d4c-7b15-11e8-90da-95303acf7bcc.png)
Does it solve your issue?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
