### ISSUE TITLE
The following build commands failed

### ISSUE THREAD

**Issue by ShagunParikh** [Backelite/sonar-swift#147]
Hi!

I am not able to run the run-sonar-swift.sh. Getting following error and I have no idea what is about.

`The following build commands failed:
    CompileSwift normal x86_64
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
ERROR - Command 'xcodebuild clean build -project Teetra.xcodeproj -scheme XYZDev-configuration Debug -destination platform=iOS Simulator,name=iPhone 6s -destination-timeout 60' failed with error code: 65`

Please help.!

**Comment by awasthiy** [comment]
Hey @ShagunParikh  ,
I am facing the same issue. Did you able to find the way to run?

**Comment by gabrielsscavalcante** [comment]
I'm facing the same problem. The build on simulator and iPhone is fine, but I cannot run sonar script... Any solutions??

**Comment by soufianeEssabbane** [comment]
Hi,
I'm having the same problem, and a lot of things not correctly working, can you please advise ? or is the library not maintained ? I used to be able to run the script and see logs in terminal but not in the web interface. 
When I run the command as in logs

> ERROR - Command 'xcodebuild clean build -workspace Particuliers.xcworkspace -scheme Particuliers-Acc -destination platform=iOS Simulator,name=iPhone 7,OS=12.1 -destination-timeout 360 COMPILER_INDEX_STORE_ENABLE=NO' failed with error code: 65

I'm getting this message among with list of available devices 

> Missing required device specifier option.
	The device type “Generic iOS Device” requires that either “name” or “id” be specified.
	Please supply either “name” or “id”.

but when I build from Xcode it works with the specified destination  device ...

please advise

**Comment by gaelfoppolo** [comment]
Closing this issue, not related to the plugin.

**Comment by ankit0409** [comment]
Same issue. Could any one please help

**Comment by ankit0409** [comment]
Same issue. Could any one please help

**Comment by ArjunSa786** [comment]
any one find solution for this.
