### ISSUE TITLE
Upgrade to SwiftLint 0.9.1

### ISSUE THREAD

**Issue by aalmazzo** [Backelite/sonar-swift#15]
SwiftLint version: 0.9.1

**Comment by akshaysyaduvanshi** [comment]
It should work with swift-lint 0.9.0.
As there is no rule added with swift-lint 0.9.0.
I am not facing any issue.

**Comment by aalmazzo** [comment]
We are getting this error message: 

Caused by: The rule 'SwiftLint:variable_name_min_length' does not exist.

**Comment by akshaysyaduvanshi** [comment]
You are using old swift-lint version then. I cant find above rule in swift-lint 0.9.1
<img width="1176" alt="screenshot 2016-03-06 01 26 42" src="https://cloud.githubusercontent.com/assets/10463665/13550057/8f39712a-e33a-11e5-83cb-40002c0ec5c6.png">

**Comment by aalmazzo** [comment]
Checking my system... Oh ruby....

**Comment by akshaysyaduvanshi** [comment]
Are you still facing issue or it is resolved??

**Comment by aalmazzo** [comment]
My bad... it was using old gems and now I'm really using 0.9.1 and it works... sorry for the trouble.
