### ISSUE TITLE
Is there interest in an extension for modular code coverage support?

### ISSUE THREAD

**Issue by isaacwang4076** [Backelite/sonar-swift#150]
I'm currently extending this plugin to:

a) Perform modular code coverage analysis
b) Give the option to specify a report directory path via sonar.swift.coverage.reportDirectory, which begins from the root of the project. E.g. if my module's base directory is a/b/c, I can still output its reports to myReportDirectory/ and specify this in my sonar-project.properties.

For some context, here is the use case for these changes that I'm working through currently. We have a multi-project setup where several different projects lie in the same repository and we want to be able to get project-specific code coverage metrics. Additionally, with the way our pipeline is set up (parallelization of different projects across many nodes), it is much more convenient to be able to specify a single reports directory for the analysis to look at (the alternative would be hackily re-inserting reports back into their corresponding directories).

I'm looking for some feedback on these changes and would like to gauge interest in them as well, with the goal of eventually landing these changes in here. Please let me know what you all think. Thanks!

**Comment by gaelfoppolo** [comment]
Closing since merged.
