### ISSUE TITLE
You must install a plugin that supports the language 'swift'

### ISSUE THREAD

**Issue by cpowell001** [Backelite/sonar-swift#153]
Hello

I have followed the `README` and am able to run the `run-sonar-swift.sh` script, however it fails at a certain point with the error: 

```
ERROR: Error during SonarQube Scanner execution
ERROR: You must install a plugin that supports the language 'swift'
```

I have placed the binary of the latest release here:
`$SONARQUBE_HOME/extensions/plugins/backelite-sonar-swift-plugin-0.3.7.jar`

Is this correct or am I missing something? 

Bellow is the output from running `sonar-scanner --version`:
```
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/3.2.0.1227/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: /Users/me/project/sonar-project.properties
INFO: SonarQube Scanner 3.2.0.1227
INFO: Java 1.8.0_162 Oracle Corporation (64-bit)
INFO: Mac OS X 10.12.6 x86_64
```

Below is the tail of the script output with full error message:
```
Done linting! Found x violations, x serious in x files.
Running Tailor...Running Lizard...Running SonarQube using SonarQube Runner
+sonar-scanner --define sonar.projectVersion=0.173.2
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/3.2.0.1227/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: /Users/me/project/sonar-project.properties
INFO: SonarQube Scanner 3.2.0.1227
INFO: Java 1.8.0_162 Oracle Corporation (64-bit)
INFO: Mac OS X 10.12.6 x86_64
INFO: User cache: /Users/me/.sonar/cache
INFO: SonarQube server 7.1.0
INFO: Default locale: "en_CA", source code encoding: "UTF-8"
INFO: Publish mode
INFO: Load global settings
INFO: Load global settings (done) | time=261ms
INFO: Server id: AWNgzVk3-sy9ka-uHKZb
INFO: User cache: /Users/me/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=65ms
INFO: Load/download plugins
INFO: Load/download plugins (done) | time=11ms
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=96ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=50ms
INFO: Load active rules
INFO: Load active rules (done) | time=599ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=48ms
INFO: Project key: project
INFO: Project base dir: /Users/me/project
INFO: -------------  Scan Project
INFO: Load server rules
INFO: Load server rules (done) | time=136ms
INFO: Base dir: /Users/me/project
INFO: Working dir: /Users/me/project/.scannerwork
INFO: Source paths: project
INFO: Test paths: projectTests
INFO: Source encoding: UTF-8, default locale: en_CA
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 3.089s
INFO: Final Memory: 13M/236M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: You must install a plugin that supports the language 'swift'
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
+returnValue=1
+set +x
ERROR - Command 'sonar-scanner --define sonar.projectVersion=0.173.2' failed with error code: 1
[me] ~/project/ l /Users/me/project

```

**Comment by raatiniemi** [comment]
I assume you have restarted your SonarQube instance after installing the plugin?

You can verify that the plugin was correctly installed by going to the Administration panel and then going to the Marketplace, there you should find the Backelite Swift plugin (there should be two Swift plugins, Backelite and the commercial from SonarSource).

**Comment by cpowell001** [comment]
@raatiniemi seems like the plugin is not supported on the free version. We upgraded and this resolved the issue. Thanks for your help.

**Comment by raatiniemi** [comment]
The plugin is indeed supported on the free version, however, if you upgrade to a paid version of SonarQube you will receive access to the SonarSource version of the plugin for the Swift programming language (among other things).

**Comment by rishbaranwal** [comment]
I think only placing backelite-sonar-swift-plugin-0.3.7.jar in $SONARQUBE_HOME/extensions/plugins is sufficient, and I restarted the SonarQube instance as well, but still I am getting this error, In  Marketplace of Administration panel, I still not able to see Backelite Swift plugin

**Comment by leonardo111994** [comment]
+1.
I got same issue, any solution?

**Comment by ashokbugude** [comment]
I have installed latest version of sonar cube 7.6 and latest version of backelite 0.4.4,
but get the below error

`You must install a plugin that supports the language 'swift'`

and the plugin is not found in sonarcube marketplace as well
 
Please help

**Comment by bianxseyer** [comment]
+1
Any solution on this?

**Comment by SiddharthPromact** [comment]
+1
Any solution on this?
