### ISSUE TITLE
must be a fat file when the -extract option is specified

### ISSUE THREAD

**Issue by lindseyvastola** [Backelite/sonar-swift#154]
I am running sonar-swift on my project and I am getting the following errors. The project runs correctly from XCode and the frameworks that the logs are complaining about are pods.

2018-08-03 11:50:19.292 xcodebuild[47834:952673] Error Domain=IDETestOperationsObserverErrorDomain Code=14 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/q9/0tb75n5n2_n0fdsldcth9vfm0000gq/T/com.apple.dt.XCTest/IDETestRunSession-ABBF8AAF-B1DA-4AB5-A71D-5A86B8DBA461/CCAppTests-87323AD6-4234-4660-B45C-7DDA58236F0A/Session-CCAppTests-2018-08-03_114859-nH075r.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/q9/0tb75n5n2_n0fdsldcth9vfm0000gq/T/com.apple.dt.XCTest/IDETestRunSession-ABBF8AAF-B1DA-4AB5-A71D-5A86B8DBA461/CCAppTests-87323AD6-4234-4660-B45C-7DDA58236F0A/Session-CCAppTests-2018-08-03_114859-nH075r.log}

Testing failed:
	Lipo: input file (/Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Reachability.framework/Reachability) must be a fat file when the -extract option is specified
	Lipo: can't open input file: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Reachability.framework/Reachability-x86_64 (No such file or directory)
	Rm: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Reachability.framework/Reachability-x86_64: No such file or directory
	Mv: rename /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Reachability.framework/Reachability-merged to /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Reachability.framework/Reachability: No such file or directory
	Lipo: input file (/Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher) must be a fat file when the -extract option is specified
	Lipo: can't open input file: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher-x86_64 (No such file or directory)
	Rm: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher-x86_64: No such file or directory
	Mv: rename /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher-merged to /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher: No such file or directory
	Lipo: input file (/Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac) must be a fat file when the -extract option is specified
	Lipo: can't open input file: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac-x86_64 (No such file or directory)
	Rm: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac-x86_64: No such file or directory
	Mv: rename /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac-merged to /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac: No such file or directory
	Lipo: input file (/Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/SwiftKeychain.framework/SwiftKeychain) must be a fat file when the -extract option is specified
	Lipo: can't open input file: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/SwiftKeychain.framework/SwiftKeychain-x86_64 (No such file or directory)
	Rm: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/SwiftKeychain.framework/SwiftKeychain-x86_64: No such file or directory
	Mv: rename /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/SwiftKeychain.framework/SwiftKeychain-merged to /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/SwiftKeychain.framework/SwiftKeychain: No such file or directory
	Lipo: input file (/Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMOAuth2.framework/GTMOAuth2) must be a fat file when the -extract option is specified
	Lipo: can't open input file: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMOAuth2.framework/GTMOAuth2-x86_64 (No such file or directory)
	Rm: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMOAuth2.framework/GTMOAuth2-x86_64: No such file or directory
	Mv: rename /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMOAuth2.framework/GTMOAuth2-merged to /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/GTMOAuth2.framework/GTMOAuth2: No such file or directory
	Lipo: input file (/Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Alamofire.framework/Alamofire) must be a fat file when the -extract option is specified
	Lipo: can't open input file: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Alamofire.framework/Alamofire-x86_64 (No such file or directory)
	Rm: /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Alamofire.framework/Alamofire-x86_64: No such file or directory
	Mv: rename /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Alamofire.framework/Alamofire-merged to /Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Products/Debug-iphonesimulator/Setec.app/Frameworks/Alamofire.framework/Alamofire: No such file or directory
	Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
	'CCServices/CCServices-Swift.h' file not found
	Failed to emit precompiled header '/Users/lindsey.vastola.cc/Library/Developer/Xcode/DerivedData/Setec-fdqdibvkiyxvknbpxvaabwfywdph/Build/Intermediates.noindex/PrecompiledHeaders/BridgingHeader-swift_1OTC38S7Q9A3M-clang_2PRDMRFAYJ2QH.pch' for bridging header '/Users/lindsey.vastola.cc/Desktop/Setec/Setec/BridgingHeader.h'
** TEST FAILED **

The following build commands failed:
	PrecompileSwiftBridgingHeader normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
-n .
ERROR - Command 'xcodebuild clean build test -workspace Setec.xcworkspace -scheme Setec -configuration Debug -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone 8,OS=11.1 -destination-timeout 60' failed with error code: 65
LVASTOLA:Setec lindsey.vastola.cc$

**Comment by zippy1978** [comment]
Hi @lindseyvastola,

This is a compilation issue with xcodebuild.
If it work in Xcode, it can be a parameter issue in sonar-project.properties (such as the workspace location).

**Comment by gaelfoppolo** [comment]
Are you still facing this issue @lindseyvastola?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
