### ISSUE TITLE
Sonarqube Server running on Linux machine won't start if I copy the plugin to $SONARQUBE_HOME/extensions/plugins directory

### ISSUE THREAD

**Issue by vighneshpai-yml** [Backelite/sonar-swift#155]
I have a sonarqube server running on a Linux machine.

I also have a Mac machine where I can configure the sonar-scanner properties to point to the Sonar Qube server running on a Linux machine.

Is it possible for me to run the analysis on a mac machine and then upload it to the server and get it displayed on the dashboard or **do I have to run the server on Mac machine itself?**

**Comment by zippy1978** [comment]
Hi @vighneshpai-yml,

There must be a compatibility issue with the plugin and your sonarQube server version.
Could you show me your sonar.log to see what fails on startup ?

**Comment by FlyingTux123** [comment]
I do have similar issues here. Installed a Sonarqube 7.3 instance and it won't start with the backelite-sonar-swift-plugin-0.4.1.jar

**Comment by jabwd** [comment]
Can't boot 7.3 on macOS either, doesn't seem to be a problem related to the platform.

```
2018.09.07 17:39:50 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/usr/local/Cellar/sonarqube/7.3/libexec]: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/usr/local/Cellar/sonarqube/7.3/libexec/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -cp ./lib/common/*:/usr/local/Cellar/sonarqube/7.3/libexec/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /usr/local/Cellar/sonarqube/7.3/libexec/temp/sq-process3876631310771213157properties
jvm 1
2018.09.07 17:40:00 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
```

**Comment by bcolvin** [comment]
I made a large amount of code changes so i'm hesitant to open a PR but if you're trying to get this working with 7.3 until its resolved officially you can try [mine](https://github.com/bcolvin/sonar-swift)

**Comment by duncillo** [comment]
Hi @bcolvin, 
You could upload the binary, or tell me how to compile it, thanks
