### ISSUE TITLE
Confused about Installation

### ISSUE THREAD

**Issue by hammer83** [Backelite/sonar-swift#156]
I'm running a Teamcity build server with the SonarQube Runner plugin installed.
And a SonarQube Server.
I've installed the sonar-swift plugin binary on the SonarQube Server.

Do I run the run-sonar-swift.sh on the build server or on the sonarqube  server?
run-sonar-swift.sh just seems to generate the report files.
How do I get the reports to the SonarQube Server?

**Comment by raatiniemi** [comment]
The `run-sonar-swift.sh` should be executed by the build server, the purpose of the script is to generate the reports and invoke `sonar-scanner` which communicate with SonarQube.

Is `sonar-scanner` installed on the build server? This can be installed using `brew install sonar-scanner`, given that you have `brew` installed.

**Comment by vickyrocky** [comment]
Hi @raatiniemi ,

Is it necessary to use sonar-scanner on mac or can we use this in windows or linux environment? I am trying to use this plugin and having sonar-scanner on windows but after analysis i am not able to see the result as it is asking for license. Any help on this would be highly apprecited.

Thanks

**Comment by vickyrocky** [comment]
Hi @raatiniemi ,

Thank you for your response! I got it and will try to look for ways to install swiftlint on windows/linux. It was asking for license because i accidently put the license plugin inside plugin folder of sonarqube and when i removed that this plugin is working fine now.
Thanks

**Comment by vickyrocky** [comment]
Hi @raatiniemi ,

After exploration i found out that i can use tailor for windows and then import that report into sonarqube using this plugin but when i did that i am not able to get any issue of tailor in sonarqube.
I did below steps:
1.created one sample swift file and placed sonar-project.properties file with content:
sonar.projectKey=swift:swift
sonar.projectVersion=1.0
sonar.projectName=swift
sonar.sources=.
sonar.swift.tailor.report=demo.json

2.ran tailor:
tailor demo.swift --format json > demo.json

3. I can see the json file with issues but not able to get that issue in sonarqube after running sonar-scanner from that directory.

Any help would be highly appreciated.
Thanks!

**Comment by raatiniemi** [comment]
Sorry, but I'm not really familiar with the tailor implementation. However, from what I've been able to understand it do not expect the format to be JSON. This is based on the fact that the default path for the report is `sonar-reports/*tailor.txt` and the implementation seem to parse line by line (which you typically don't do for JSON). I'm not certain as to what tailor format would produce a `.txt` file.

**Comment by Aya-Akl** [comment]
I have a question here, if we are using bamboo as the CI server and using the sonarscanner executable to run sonar-scanner, this should be working and giving all the reports like swiftlint? or there is another configuration regarding `run-sonar-swift.sh` I should do?
