### ISSUE TITLE
Jenkins Build Failure after installing Backlite Objective C plugin in Sonarqube

### ISSUE THREAD

**Issue by yramya20** [Backelite/sonar-swift#158]
Hello,

I’m using Sonarqube version 6.2 and installed freeware backlite objective C plugin in sonarqube.

After installing this plugin in sonarqube when we were trying to build projects (maven) using jenkins, builds failed with the below error:

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.1.1168:sonar (default-cli) on project cwow-parent-maven: Unable to register extension org.sonar.plugins.objectivec.ObjectiveCSquidSensor from plugin 'backelitesonarobjectivecplugin': Lorg/sonar/api/checks/AnnotationCheckFactory;: org.sonar.api.checks.AnnotationCheckFactory -&gt; [Help 1]

Kindly help on how do resolve this issue as we need objective C plugin to be installed for a requirement.

**Comment by andrewclaus** [comment]
I believe this Swift plugin now includes the old Objective-C plugin? There is a note in the 0.4.0 release notes: 
"Objective-C support (merged from our Objective-C plugin). When upgrading to this version you must install OCLint (brew install oclint). If you used our Objective-C plugin, you must uninstall it (remove it from /extensions/plugins directory)."

So if you update to 0.4.0 or greater, you can remove the objective-C plugin and it should work for both languages (have yet to test it out myself).
