### ISSUE TITLE
Installing the plugin on linux

### ISSUE THREAD

**Issue by Xflofoxx** [Backelite/sonar-swift#16]
Hi, I already have a SonarQube server running on linux.
How can I install your plugin on it?
I try putting the .jar inside $SONARQUBE_HOME/extensions/plugins but nothing happens.

I'm using SonarQube Version 5.3.

Any advice?
Thank you.
Dario

**Comment by Xflofoxx** [comment]
Sorry, wrong directory :dancers:

**Comment by NonCreature0714** [comment]
What was the correct directory?

**Comment by Xflofoxx** [comment]
$SONARQUBE_HOME/extensions/plugins was the right directory, I put them in a wrong one 🗡

**Comment by NonCreature0714** [comment]
Oh good, I was worry there for a sec
