### ISSUE TITLE
No line highlight of code coverage?

### ISSUE THREAD

**Issue by Shinwar** [Backelite/sonar-swift#164]
I build and test a swift project and run  run-sonar-swift.sh. It uploaded unit test successfully and showed me code coverage rating. But I found when I click on "Lines to Cover" or "Uncovered Lines". It always show all codes and there is no coverage highlight.
![image](https://user-images.githubusercontent.com/6257650/45135692-51990a00-b1d3-11e8-8ddc-4360d3904b01.png)

**Comment by zhaoyubetter** [comment]
the same

**Comment by zhaoyubetter** [comment]
No line highlight of code coverage
