### ISSUE TITLE
Sonar-Swift 0.4.1 not reporting OBJC issues on SonarQube LTS (6.7.4)

### ISSUE THREAD

**Issue by CRoig** [Backelite/sonar-swift#169]
According to the documentation of 0.4.0, objc plugin has been merged, so I had to remove it from the plugins folder. I noticed that if both plugins are added, sonarqube fails during the launching.

So, I removed objective c plugin and added 0.4.1. I found out all objective c identified by oclint are not added although I have OCLINT profile selected for ObjC. 

Is this a know issue? Should I move to SonarQube 7.3?

**Comment by gaelfoppolo** [comment]
Do you still face this issue with the current version of the plugin?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
