### ISSUE TITLE
error: Failed to load coverage: No such file or directory

### ISSUE THREAD

**Issue by chaosnya** [Backelite/sonar-swift#17]
Hello,

I tried this sonar plugin with projects using or not CocoaPod and a new project from scratch. Every-time i get the following error :

> /Library/Ruby/Gems/2.0.0/gems/slather-1.8.1/lib/slather/project.rb:142:in `profdata_llvm_cov_output': No Coverage.profdata files found. Please make sure the "Code Coverage" checkbox is enabled in your scheme's Test action or the build_directory property is set.
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-1.8.1/lib/slather/project.rb:98:in `profdata_coverage_files'
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-1.8.1/lib/slather/project.rb:75:in `coverage_files'
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-1.8.1/lib/slather/coverage_service/cobertura_xml_output.rb:17:in `post'
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-1.8.1/bin/slather:80:in `post'
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-1.8.1/bin/slather:46:in `execute'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
> 	from /Library/Ruby/Gems/2.0.0/gems/slather-1.8.1/bin/slather:6:in `<top (required)>'
> 	from /usr/local/bin/slather:23:in `load'
> 	from /usr/local/bin/slather:23:in `<main>'
> ERROR - Command 'slather coverage --input-format profdata -i .*Tests.* --cobertura-xml --output-directory sonar-reports --scheme TestSonar TestSonar.xcodeproj' failed with error code: 1

I checked, the "Coverage.profdata" file exists on derived data directory.
Another developer from my company obtained the same result on other projects.
I working with XCode 7.3 (same issue with 7.2.1) on El capitan.

Any idea ?

the only workaround i found, is to comment the following line on the run script :
```
runCommand /dev/stdout $SLATHER_CMD coverage --input-format profdata $excludedCommandLineFlags --cobertura-xml --output-directory sonar-reports --scheme "$appScheme" $firstProject
mv sonar-reports/cobertura.xml sonar-reports/coverage.xml
```

**Comment by RxCAI** [comment]
The same problem occurs, Xcode 7.3, anyone has found something works?

**Comment by chaosnya** [comment]
Try to remove

> --scheme "$appScheme"

on the run-sonar-swift.sh file, it's working for me.

**Comment by RxCAI** [comment]
Thanks @chaosnya , it works for me as well!!!

**Comment by zippy1978** [comment]
Hi,

Since Xcode 7.3 Apple changed location of coverage data.
slather (the tool used for coverage need to be updated).

At the moment, you can get the run-sonar.swift.sh from the develop branch and install slather from its repository master branch (https://github.com/SlatherOrg/slather) and it will work again.

I will release a new version of the plugin as soon as a new version of slather is released.

**Comment by grevolution** [comment]
slather 2.1.0 is supposed to fix the issue and also seems to work with the plugin.

**Comment by zippy1978** [comment]
Yes !
I updated the README.md for slather install instructions (a simple 'gem install slather' is enough now).
The run script was also updated (but not need to upgrade the plugin on the SonarQube server).
