### ISSUE TITLE
If I want to start the analysis from Bamboo

### ISSUE THREAD

**Issue by Aya-Akl** [Backelite/sonar-swift#190]
If I want to start the analysis from Bamboo, how I should run this? I should run it by running a shell command to run `run-sonar-swift.sh` script from our Xcode project root folder or what I should do please I am so confused in this step, because everything seems to be working except for swiftlint rules are not working

**Comment by gtatgh** [comment]
@Aya-Akl yes, user shell-Interpreter and file as "Script Location". Be sure the commands are in path of Bamboo.

**Comment by gaelfoppolo** [comment]
Does it solve your issue @Aya-Akl?

**Comment by davidy4ng** [comment]
No updates on the issue for a while now. I'm closing.
