### ISSUE TITLE
Absence of data in bugs and vulnerabilities section

### ISSUE THREAD

**Issue by soufianeEssabbane** [Backelite/sonar-swift#191]
Hi
**Describe the bug**
after configuring (I think) correctly Sonar-swift once I start the analyse I'm not able to get the "bugs and vulnerabilities" on my dashboard it's always showing 0

**To Reproduce**
1. Go to your project folder
2. run run-sonar-swift
3. open sonarqube dashboard
4. See missing data from "bugs and vulnerabilities" it's always showing 0

**Expected behavior**
Dashboard with all metrics and "bugs & vulnerabilities"

**Screenshots**
<img width="1322" alt="screenshot 2018-12-17 at 02 03 50" src="https://user-images.githubusercontent.com/1910912/50156430-1d9fab80-02cf-11e9-8e9d-2d3d1124f2b9.png">

**SonarQube environment:**
 - OS: MacOS
 - Version 6.7.6
- plugin version : 0.4.2

Please assist

**Comment by gaelfoppolo** [comment]
Hi @soufianeEssabbane,
The plugin doesn't have any rule about bugs or vulnerabilities yet.
Feel free to participate in adding some 🙂

**Comment by nanshanyi** [comment]
I have the same problem ，I use jenkins。
I tried other language，it works well

**Comment by soufianeEssabbane** [comment]
@gaelfoppolo I would love to but not sure how to :)

**Comment by soufianeEssabbane** [comment]
@nanshanyi  do you mean that you are able to get that for other languages but not for swift ?

**Comment by nanshanyi** [comment]
@soufianeEssabbane Yes ，I tried Python it works well. But now I don't use  SonarQube Scanner for Jenkins , I use the script directly, it works well.
Thank you for your reply！

**Comment by gaelfoppolo** [comment]
Duplicate of #101. Closing this one.

**Comment by maximepmr** [comment]
> Duplicate of #101. Closing this one.
Stop saying that it is duplication, subject 101 speaks of a version 0.3.5 but if you have a higher version the problem comes from elsewhere ...

**Comment by davidy4ng** [comment]
> > Duplicate of #101. Closing this one.
> > Stop saying that it is duplication, subject 101 speaks of a version 0.3.5 but if you have a higher version the problem comes from elsewhere ...

I think it is the same issue if you reach the end of the thread.

https://github.com/Backelite/sonar-swift/issues/101#issuecomment-335408163
