### ISSUE TITLE
xcodebuild: command not found

### ISSUE THREAD

**Issue by PetreToma** [Backelite/sonar-swift#197]
Hi

I have SonarQube 7.4 on Ubuntu and I add "backelite-sonar-swift-plugin-0.4.3.jar" plugin build on server. 

On same machine I have the swift project and I set up the properties files, but when I run "run-sonar-swift.sh" I get this error:

./run-sonar-swift.sh: line 106: xcodebuild: command not found
+ returnValue=127

I have this questions:
1. Is possible to run scanner on Linux (Ubuntu) for a project "swift" project? or I need a Mac system.
2. If yes .. What setting and what I have to install to do it on Ubuntu (I have Lizard, Tailor installed)

**Comment by gaelfoppolo** [comment]
Hi @PetreToma,
You need a Mac.

**Comment by davidy4ng** [comment]
Analysis tools are build upon xcodebuild command line tools, which requires a Mac.

You're SonarQube setup is probably right. But you need to run analysis on a Mac.
