### ISSUE TITLE
Problem with Bugs and Vulnerabilities in Qube

### ISSUE THREAD

**Issue by yezixcc** [Backelite/sonar-swift#204]
Can't detect Bugs and Vulnerabilities

**Comment by ViniciusGibran** [comment]
Same problem here! We're using Lizard & SwiftLint rules as our project has no tests yet, but it gives code smells only.. We appreciate any help. Thank you!

**Comment by pedroroberto** [comment]
Same problem here!

**Comment by gaelfoppolo** [comment]
Duplicate of #101. Closing this one.
