### ISSUE TITLE
Sonar script fails with No module found "Google maps" and destination timeout, using Pods.

### ISSUE THREAD

**Issue by SavitaJuyal** [Backelite/sonar-swift#21]

**Comment by zippy1978** [comment]
Hi @SavitaJuyal,
You need to set the correct workspace in you sonar-project.properties.
But... your problems seems to be related to Google Maps pod.
When sonar script is running, your application is built in Debug for the Simulator (not the same arch as a real device). 
Did you try building and running you app on the simulator to check if you have the problem ?

Regards,
Gilles

**Comment by SavitaJuyal** [comment]
Hi,

No my project is running successfully in all devices and simulator but 
not with SonarQube. I have attached the project properties settings for 
my project, please check and tell me know if I am missing something.

On 5/6/16 2:27 AM, Gilles Grousset wrote:
>
> Hi @SavitaJuyal <https://github.com/SavitaJuyal>,
> You need to set the correct workspace in you sonar-project.properties.
> But... your problems seems to be related to Google Maps pod.
> When sonar script is running, your application is built in Debug for 
> the Simulator (not the same arch as a real device).
> Did you try building and running you app on the simulator to check if 
> you have the problem ?
>
> Regards,
> Gilles
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/Backelite/sonar-swift/issues/21#issuecomment-217277727>
>


##########################
# Required configuration #
##########################

sonar.projectKey=com.netsolutions
sonar.projectName=Friendin
sonar.projectVersion=1.0
# Comment if you have a project with mixed ObjC / Swift
sonar.language=swift
sonar.profile=SwiftLint
 
# Project description
sonar.projectDescription=FriendIn
 
# Path to source directories 
sonar.sources=/Users/savitajuyal/Desktop/Friendin
# Path to test directories (comment if no test)
#sonar.tests=TestDir

# Destination Simulator to run tests
# As string expected in destination argument of xcodebuild command
# Example = sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=9.2
sonar.swift.simulator=platform=iOS Simulator,name=iPhone 5,OS=9.3
 
# Xcode project configuration (.xcodeproj)
# and use the later to specify which project(s) to include in the analysis (comma separated list)
# Specify either xcodeproj or xcodeproj + xcworkspace
sonar.swift.project=Friendin.xcodeproj
sonar.swift.workspace=Friendin.xcworkspace

# Scheme to build your application
sonar.swift.appScheme=Friendin
 
##########################
# Optional configuration #
##########################

# Encoding of the source code
sonar.sourceEncoding=UTF-8


# SCM
# sonar.scm.enabled=true
# sonar.scm.url=scm:git:http://xxx

# JUnit report generated by run-sonar.sh is stored in sonar-reports/TEST-report.xml
# Change it only if you generate the file on your own
# The XML files have to be prefixed by TEST- otherwise they are not processed 
# sonar.junit.reportsPath=sonar-reports/

# Lizard report generated by run-sonar.sh is stored in sonar-reports/lizard-report.xml
# Change it only if you generate the file on your own
# sonar.swift.lizard.report=sonar-reports/lizard-report.xml

# Cobertura report generated by run-sonar.sh is stored in sonar-reports/coverage.xml
# Change it only if you generate the file on your own
# sonar.swift.coverage.reportPattern=sonar-reports/coverage*.xml

# OCLint report generated by run-sonar.sh is stored in sonar-reports/oclint.xml
# Change it only if you generate the file on your own
# sonar.swift.swiftlint.report=sonar-reports/*swiftlint.txt

# Paths to exclude from coverage report (tests, 3rd party libraries etc.)
# sonar.swift.excludedPathsFromCoverage=pattern1,pattern2
sonar.swift.excludedPathsFromCoverage=.*Tests.*

**Comment by SavitaJuyal** [comment]
Hi @zippy1978 ,

Please revert asap.

Regards
Savita
