### ISSUE TITLE
Found why backelite-sonar-swift plugin does not show Bugs and Vulnerabilities

### ISSUE THREAD

**Issue by Piduna** [Backelite/sonar-swift#211]
First of all, i want to say thanks. Thanks for your great job, that you are making this plugin for free.
On this git repository in `issues` area a lot of issues according to `Bugs` and `Vulnerabilities` that are `0`. I have seen, that i am not alone in this question. I made a lot of researchings. I thought, that there were a problem with parsing or with writing in database. The reason was easier.

![изображение](https://user-images.githubusercontent.com/13176563/54948738-0dd6d980-4f46-11e9-9c67-703ca0e7eb32.png)

Do you see, 292 bugs ? Now please press on `Bug`, like here

![изображение](https://user-images.githubusercontent.com/13176563/54948158-a79d8700-4f44-11e9-9e3a-a023a3a1b8ba.png)

Do you see, that we have only 2 bugs with `objective c` and `swift`. Let's look on `Vulnerabilities`

![изображение](https://user-images.githubusercontent.com/13176563/54948302-fcd99880-4f44-11e9-8590-31e4a3a65115.png)

How we can see, there are no `objective c` and `swift`. 

I mean, that problem, that you wrote all rules in `Code smells` category. I suggest You to update your plugin according to `Bugs` and `Vulnerabilities`. Thanks again for your great job. We are waiting for new version of plugin.

**Comment by ViniciusGibran** [comment]
"they had us in the first half not gonna lie.."

**Comment by egr-ext** [comment]
How can you flag a code smells as a bug in the plugin code ?
I don't see any category in profile-oclint.xml ....

**Comment by gaelfoppolo** [comment]
Duplicate of #101. Closing this one.
