### ISSUE TITLE
Coverage on New Code not showing (always "-")

### ISSUE THREAD

**Issue by egr-ext** [Backelite/sonar-swift#219]
**Describe the bug**
The Coverage **on New Code** is not showing. It always shows "-".

**To Reproduce**

1. Run a sonar scanner on version 1.0 of a project
2. Add some new code and tests. Commits
3. Run a sonar scanner on version 1.1 of the project
4. On SonarQube, the dashboard displays all indicators on new code but nothing for coverage on new code

**Expected behavior**
Showing the indicator Coverage on New Code different from "-" when tests are added to new code.

**Screenshots**

**SonarQube environment:**
 - OS: MacOS
 - Version 7.2.1

**Comment by egr-ext** [comment]
Fixed

**Comment by sindhusanga-git** [comment]
How did you fix it? I am facing the same issue.

**Comment by egr-ext** [comment]
Hi, 

Using Fastlane , I fixed wrong file name and directory path.
