### ISSUE TITLE
update to swiftlint 0.10

### ISSUE THREAD

**Issue by rompic** [Backelite/sonar-swift#22]
i had to disable legacy_cggeometry_functions using a
.swiftlint.yml file in order to get it to work with swiftlint 0.10:

disabled_rules: # rule identifiers to exclude from running
 - legacy_cggeometry_functions

**Comment by zippy1978** [comment]
Thanks :)
Didn't know Swiftlint 0.10 was released yet...
I will add the missing rule soon...

**Comment by zippy1978** [comment]
Hi,

I just pushed SwiftLint 0.10.0 support on develop branch...
