### ISSUE TITLE
Missing build-wrapper-report.json file

### ISSUE THREAD

**Issue by pfaucon** [Backelite/sonar-swift#221]
**Describe the bug**
```
ERROR: java.nio.file.NoSuchFileException: /<<PROJ>>/sonar-reports/build-wrapper-dump.json
ERROR: Caused by: /<<PROJ>>/sonar-reports/build-wrapper-dump.json
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

This file is created by build-wrapper-macosx-x86 (or whatever OS/arch you have) but I don't see any reference to it in the script.

**To Reproduce**
have a project, try to run run-sonar-swift.sh, it should fail with this error eventually (I disabled a lot of other things to get to this point, lizard/unit test)

**Expected behavior**
The file should be generated by running the build-wrapper, allowing sonar-scanner to complete

**SonarQube environment:**
 - OS: OS X 10.14.2
 - Version Trying to use SonarCloud eventually, but I don't think that is relevant at this point in the process

**Comment by gaelfoppolo** [comment]
The issue does not seem related to the plugin.
Try using the regular SonarQube before using SonarCloud.

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
