### ISSUE TITLE
failed with error code: 64

### ISSUE THREAD

**Issue by onmyway133** [Backelite/sonar-swift#222]
**Describe the bug**
After successfully install plugin and add `run-sonar-swift.sh`, when running it I get

```
ERROR - Command 'xcodebuild clean build -workspace 'MyApp.xcworkspace' -scheme 'MyApp Staging' -destination 'platform=iOS Simulator,name=iPhone Xʀ' -destination-timeout 360 COMPILER_INDEX_STORE_ENABLE=NO' failed with error code: 64
``` 

If I run that xcodebuild command alone, it runs perfectly

**SonarQube environment:**
 - OS: macOS Mojave
 - Version 10.14

**Additional context**
Mine is a swift 5 iOS project using Xcode 10

**Comment by oneGain** [comment]
+1, Anybody have any ideas？

**Comment by oneGain** [comment]
most the same as you  
OS: macOS Mojave
swift 4.2
xcode 10.2.1
but `failed with error code: 65 `
Anybody have any ideas?

**Comment by oneGain** [comment]
I find my buid configuration have changed 
So, write sonar.swift.appConfiguration=MYbug
It works

**Comment by reden87** [comment]
Same issue here:
* I see the same error mesage
* If I run the command alone it builds successfully
* I'm using `Swift 4.2`
* `Xcode 10.1`
* `macOS Mojave 10.14.5`

**Comment by gaelfoppolo** [comment]
Please open your own issue @reden87.
Closing this one.
