### ISSUE TITLE
LizardReportParser$SwiftFunction cannot be cast to DefaultInputComponent with Sonarqube 7.7

### ISSUE THREAD

**Issue by sandeepbol** [Backelite/sonar-swift#225]
The scan exits with the following error:
```
ERROR: Error during SonarQube Scanner execution
ERROR: com.backelite.sonarqube.swift.complexity.LizardReportParser$SwiftFunction cannot be cast to org.sonar.api.batch.fs.internal.DefaultInputComponent
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
+ returnValue=1
+ set +x
ERROR - Command 'sonar-scanner ' failed with error code: 1
```

**SonarQube environment:**
 - OS: MacOS Mojave 10.14.4 (18E226)
 - Version 7.7
 - Sonar-scanner 3.3.0.1492

The backelite sonar-swift plugin is compiled manually by pulling the latest [release](https://github.com/Backelite/sonar-swift/commit/42831ead6a8e838fe5db28b0430c77209b72603f) 0.4.4 code.

**Comment by wods** [comment]
same issue here.
SonarQube Scanner 3.3.0.1492
Java 12.0.1 Oracle Corporation (64-bit)
Mac OS X 10.14.5 x86_64
Version 7.7

**Comment by sandeepbol** [comment]
@wods he asks to run lizard manually but after running lizard, sonar-scanner will overwrite sonar-reports. So didn't understand his point actually. This looks clearly like a bug and should be handled properly.

**Comment by wods** [comment]
> @wods he asks to run lizard manually but after running lizard, sonar-scanner will overwrite sonar-reports. So didn't understand his point actually. This looks clearly like a bug and should be handled properly.

Yes, same issue here. The tip doesn't work. I'm looking for the solution too.

**Comment by wods** [comment]
One silly method is to comment "addComplexityFunctionMeasures(new SwiftFunction(name),values);" in LizardReportParser.java

**Comment by sandeepbol** [comment]
That's correct @wods but this is really weird as when I try to see the usage of `org.sonar.api.batch.fs.internal.DefaultInputComponent` in the project, I can't find any. And, in case, I missed out, both `SwiftFunction` and `DefaultComponent` implements `InputModule`. Why does Polymorphism go for a toss here?

**Comment by bcolvin** [comment]
@sandeepbol I was stumped on this for awhile too, but its because they're name might be the same, but they're in different libs iirc Good luck
https://github.com/bcolvin/sonar-swift/commit/794c8f4ef76ee559a1af5f34cbbbc5943ca65503

**Comment by sandeepbol** [comment]
@bcolvin many thanks. I pulled your repo and did an `mvn clean install`. The scan works beautifully!! When is this going to be merged?

**Comment by nishabe** [comment]
@bcolvin's fix worked for me.
Thanks!

**Comment by gaelfoppolo** [comment]
Should be fixed by https://github.com/Backelite/sonar-swift/pull/180. Awaiting merge.

**Comment by shuaibimran** [comment]
when it will be merged in to this repository?. @bcolvin do you have any idea

**Comment by bcolvin** [comment]
https://github.com/Backelite/sonar-swift/pull/243 though I did not increase the version to 7.7 @gaelfoppolo might want to handle that

**Comment by shuaibimran** [comment]
thank you so much @bcolvin. you just save my life. I really thankful to you.

**Comment by davidy4ng** [comment]
Merged in develop. Awaiting new release. Thanks @bcolvin
