### ISSUE TITLE
Unable to integrate with Jenkins SonarQube plugin

### ISSUE THREAD

**Issue by mohamedgalalcs** [Backelite/sonar-swift#226]
I am able to run SonarQube normally by running the script **run-sonar-swift. sh** from the project directory, after that, I installed Jenkins and my project is running normally on Jenkins and build normally, but the problem is when I installed the SonarQube plugin on Jenkins, I'm not able to get SonarQube work from Jenkins because Jenkins by default is running **sonar-scanner** script instead of **run-sonar-swift.sh**.

How can I fix this? Shall I neglect the SonarQube plugin and just run the script as shell script from Jenkins? Or there is another way to fix this?

**Comment by davidy4ng** [comment]
I don't know about the sonar plugin on Jenkins, but yes, you should use the run-sonar-swift.sh.

Basically it just launch build, tests, get a junit report, gather coverage data with slather, get a complexity report with lizard, get a report from different linters (oclint, swiftlint, tailor) and then launch sonar-scanner.

If you want to use the Jenkins plugin, I suppose you have to manage getting all of these reports and then use Jenkins Sonar plugin, which I guess just run sonar-scanner.

**Comment by gaelfoppolo** [comment]
Does it solve your issue @mohamedgalalcs?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
