### ISSUE TITLE
xcodebuild: error: Scheme napos is not currently configured for the test action.

### ISSUE THREAD

**Issue by pangyingchen** [Backelite/sonar-swift#227]
**sonar-project.properties**
sonar.projectKey=naposKey
sonar.projectName=naposName
sonar.projectVersion=1.0
sonar.language=swift
sonar.projectDescription=prjDescription
sonar.sources=****/gitWorkspace/morrowind/napos
sonar.swift.simulator=platform=iOS Simulator,name=iPhone 7,OS=12.2
sonar.swift.project=napos.xcodeproj
sonar.swift.workspace=napos.xcworkspace
sonar.swift.appScheme=napos
sonar.sourceEncoding=UTF-8
sonar.swift.excludedPathsFromCoverage=.*Tests.*

**run-sonar-switf.sh**

▸ Running script '[CP] Copy Pods Resources'
▸ Touching napos.app (in target: napos)
▸ Build Succeeded
actual = 24360169, min = 3
-n Running surefire

+ xcodebuild clean build test -workspace napos.xcworkspace -scheme napos -configuration Debug -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.2' -destination-timeout 60
2019-06-06 16:34:25.598 xcodebuild[47372:877149] +dataWithFirstBytes:1024 ofFile:"******/napos/Pods/TBRest/TBRest.framework/.gitkeep" failed, errno = 2
xcodebuild: error: Scheme napos is not currently configured for the test action.

+ returnValue=66
+ set +x
ERROR - Command 'xcodebuild clean build test -workspace napos.xcworkspace -scheme napos -configuration Debug -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone 7,OS=12.2 -destination-timeout 60' failed with error code: 66

运行sh脚本，抛如上异常，大家有遇到过吗，有什么解决建议吗

**Comment by derekibw** [comment]
I have the same problem, did you have solved?

**Comment by davidy4ng** [comment]
Are you able to run your unit tests with the given command line?

```xcodebuild clean build test -workspace napos.xcworkspace -scheme napos -configuration Debug -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.2' -destination-timeout 60```

Also, check if your test scheme is set to Shared.

**Comment by gaelfoppolo** [comment]
Does it solves your issue @pangyingchen @derekibw?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
