### ISSUE TITLE
oclint does't work

### ISSUE THREAD

**Issue by pangyingchen** [Backelite/sonar-swift#228]
**run-sonar-swift.sh**
sh ./run-sonar-swift.sh

Skipping Tailor!
-n Running OCLint...

-n Path included in oclint analysis is: --include /*****/napos

+ oclint-json-compilation-database -v --include /*****/napos -- -rc LONG_LINE=250 -max-priority-1 10000 -max-priority-2 10000 -max-priority-3 10000 -report-type pmd -o sonar-reports/_Users_pangyingchen_Desktop_src_gitWorkspace_morrowind_napos-oclint.xml
Skipping FauxPas
Skipping Lizard (test purposes only!)
-n Running SonarQube using SonarQube Scanner

but can't find "_Users_pangyingchen_Desktop_src_gitWorkspace_morrowind_napos-oclint.xml"

**Comment by gaelfoppolo** [comment]
What is your version of OCLint ?
Can you provide the folder structure of your project?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
