### ISSUE TITLE
Running run-sonar-swift.sh on linux returns an error command not found

### ISSUE THREAD

**Issue by bianxseyer** [Backelite/sonar-swift#230]
I am trying to follow this tutorial to use sonarswift: https://saytech48.wordpress.com/2018/04/03/sonarqube-integration-for-swift/comment-page-1/?unapproved=45&moderation-hash=f88ce1338ef6b961a242da4650d91ee5#comment-45

As I try to do the code analysis part (Item #13), I get sudo: ./run-sonar-swift.sh: command not found

I'm a newbie here and any help would be appreciated. Thanks

**Comment by davidy4ng** [comment]
You should provide more information, logs or console output.

**Comment by gaelfoppolo** [comment]
Without any response, this issue will be closed.

**Comment by davidy4ng** [comment]
Referring to the issue title, I would like to inform you that the sonar analysis and the mentioned script should be run on a Mac: it uses Xcode command line tools (xcodebuild) which only runs on a Mac.

I'm closing this issue.
