### ISSUE TITLE
objective OClint

### ISSUE THREAD

**Issue by Tiny0529** [Backelite/sonar-swift#240]
My project language is objective-c 
use fastlane
oclint.xml has been created
when I use the sonar this is a question
I can get the coverage but I can't get oclint result

sonar version 7.0
Xcode version 10.2.1

sonar.swift.coverage.reportPattern=reports/cobertura.xml
sonar.swift.oclint.reportPath=reports/oclint.xml

**Comment by gaelfoppolo** [comment]
Please provided more information (logs), or we will not be able to help you.

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
