### ISSUE TITLE
The rule 'SwiftLint:legacy_cggeometry_functions' does not exist

### ISSUE THREAD

**Issue by giacgbj** [Backelite/sonar-swift#25]
Running SonarQube using SonarQube Runner..
ERROR: Error during SonarQube Scanner execution
ERROR: The rule 'SwiftLint:legacy_cggeometry_functions' does not exist.

The error occurs if I install swiftlint 0.10.0, while it works using the version 0.9.2.

**Comment by rompic** [comment]
See https://github.com/Backelite/sonar-swift/issues/22

**Comment by giacgbj** [comment]
Thanks, moreover, now I learnt how to disable rules :-)
