### ISSUE TITLE
How to Run Sonar using Device instead of simulator ?

### ISSUE THREAD

**Issue by AnitaVPN** [Backelite/sonar-swift#252]
I am successfully able to install the solar project in my pc, but I want to perform a test on the device, instead of simulator 

I found the key for simulator configuration is: sonar.swift.simulator 

Do we have any key respect for the device as well?

Need urgent help

Much appreciated !!

**Comment by davidy4ng** [comment]
This key is then injected in the -destination parameter of the xcodebuild command.
Try something like this if you want to run it on a device.
