### ISSUE TITLE
OClint not working anymore with XCode 11

### ISSUE THREAD

**Issue by egr-ext** [Backelite/sonar-swift#254]
I post here because I don't have any answer on the oclint github project: https://github.com/oclint/oclint/issues/547

Since Xcode 11 arrived, Oclint is générating the report anymore:

- It generates "Many warning with "N error generated"
- crash on "oclint: error: cannot open report output file /Users/***/sonar-reports/oclint.xml"

Is anyone found a solution ?

I have to run sonar analysis with the version 10 of Xcode to be able to get reports.

**Comment by skywancen** [comment]
You can try this : https://github.com/oclint/oclint/pull/548

**Comment by egr-ext** [comment]
Thanks it work
