### ISSUE TITLE
run-sonar-swift.sh exit 0

### ISSUE THREAD

**Issue by giacgbj** [Backelite/sonar-swift#26]
In my opinion, in https://raw.githubusercontent.com/Backelite/sonar-swift/master/src/main/shell/run-sonar-swift.sh, after the second occurrence of the line

`echo "ERROR - Command '$command $@' failed with error code: $returnValue"`

you should replace 

`exit $?`

with

`exit $returnValue`

This way it won't always exit with 0 :-)

**Comment by zippy1978** [comment]
Thanks,

I modified the script on develop branch.

Should be released soon.
