### ISSUE TITLE
-bash: ./run-sonar-swift.sh: Permission denied

### ISSUE THREAD

**Issue by chandansingh5** [Backelite/sonar-swift#267]
I have successfully started the localhost. I have added `run-sonar-swift.sh` and `sonar-project.properties`. After I try to run the command(`./run-sonar-swift.sh`) on the terminal. It says Permission denied. Let me know if any input required. Thanks in advance.

**Comment by luisfernandezbr** [comment]
Hi @chandansingh5 .

Seems that you need to run `chmod [something] run-sonar-swift.sh` to enable the permission.

Please check https://cets.seas.upenn.edu/answers/chmod.html
 I hope this helps.
