### ISSUE TITLE
slather error find_binary_files

### ISSUE THREAD

**Issue by croccio** [Backelite/sonar-swift#27]
-n Computing coverage report
-n .
/Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:445:in `find_binary_files': No product binary found in /Users/antonio/Library/Developer/Xcode/DerivedData/Qui-bytbtjdboajwjvdreycwlxvvniqo/Build/Intermediates/CodeCoverage. (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:337:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/project.rb:240:in `configure'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/lib/slather/command/coverage_command.rb:48:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.2.0/bin/slather:15:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
ERROR - Command 'slather coverage --input-format profdata -i .*Tests.* --cobertura-xml --output-directory sonar-reports --workspace Qui.xcworkspace --scheme QUI! Collaudo Esterno Qui.xcodeproj' failed with error code: 1

**Comment by viteinfinite** [comment]
Hi @croccio, you should look for help in the slather's issues. Still, it looks like your scheme name isn't correct.

**Comment by croccio** [comment]
thanks
