### ISSUE TITLE
[enhancement] Favour Fastlane instead of .sh script 

### ISSUE THREAD

**Issue by viteinfinite** [Backelite/sonar-swift#29]
Maybe this is just my personal opinion, but I really prefer using sonar with Fastlane (and there's even an action for that). The entire Fastlane script counts 5/6 lines of code and it's easily readable. In contrast, the bundled `.sh` script is somehow complex, in particular for less advanced users, and errors are not easily debuggable.

Personally, I would document an example of Fastlane+Sonar in the main `README.md` page and reduce the relevance of - or completely hide - the `run-sonar-swift.sh` script.

Here is an example of my `sonar` lane in the `Fastfile`:
```ruby
  lane :sonar do
    scan(scheme: "TestProject", code_coverage: true, xcargs: "-derivedDataPath ./DerivedData", output_directory: "./reports")
    slather(cobertura_xml: true, jenkins: true, scheme: "TestProject", output_directory: "./reports", build_directory: "./DerivedData", binary_basename: "TestProject", proj: "./TestProject.xcodeproj")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    sh("lizard TestProject -l swift --xml > ../reports/lizard-report.xml")
    sonar
  end
```
The lane above almost completely replaces the 320-line `run-sonar-swift.sh` script and is more easily configurable: please note, for instance, the `xcargs`passed to the `scan` action.

What do you think? I'd be happy to edit the README file if you guys agree.

**Comment by rompic** [comment]
+1

**Comment by aalmazzo** [comment]
+1 we use fast lane at the NFL and this fits our deployment pipeline

- Antonio Almazzo

**Comment by zippy1978** [comment]
Hi @viteinfinite,
I was thinking of getting rid of the sh script.... This is a good idea !

I'm not familiar with Fastlane but I will have a look, or you can issue a PR :)

Gilles

**Comment by xfreebird** [comment]
@viteinfinite I think we would need to add and a step to create the oclint report

**Comment by giacgbj** [comment]
In order to use swiftlint you can simply use the swiftlint action (https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/swiftlint.rb) or a simple sh action like the one used for lizard.
I preferred the latter because it seems that we can't pass a path (--path) from the swiftlint action to the swiftlint command and I think that using the parameter "files" is extremely troublesome.

**Comment by viteinfinite** [comment]
@giacgbj I somehow forgot the `swiftlint` line in my example above. It's fixed now.

```ruby
  lane :sonar do
    scan(scheme: "TestProject", code_coverage: true, xcargs: "-derivedDataPath ./DerivedData", output_directory: "./reports")
    slather(cobertura_xml: true, jenkins: true, scheme: "TestProject", output_directory: "./reports", build_directory: "./DerivedData", binary_basename: "TestProject", proj: "./TestProject.xcodeproj")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    sh("lizard TestProject -l swift --xml > ../reports/lizard-report.xml")
    sonar
  end
```

**Comment by gooner22** [comment]
@viteinfinite do you have "number of tests" section updated on sonar?
I get 0 when use fastlane instead of .sh script

Looks like .junit report is not wired properly

**Comment by giacgbj** [comment]
@gooner22 It seems related to #28.

**Comment by gooner22** [comment]
@giacgbj thanks!

**Comment by zippy1978** [comment]
Hi,

Fastlane test report naming (.junit) is not compliant with expected .xml files.
I just pushed and update on develop branch to take in account .juint reports as well.
