### ISSUE TITLE
Unable to execute sonar - The rule 'SwiftLint:valid_docs' does not exist.

### ISSUE THREAD

**Issue by gretzki** [Backelite/sonar-swift#3]
SwiftLint 0.5.1
Sonar-Swift 0.1.1

This will happen after every update of SwiftLint.
Perhaps Sonar-Swift should be configured to ignore unknown rules?
Cheers,
Chris

**Comment by zippy1978** [comment]
Hi,

sonar-swift 0.1.1 is not compliant with SwiftLint > 0.4
I just released version 0.1.2 that should be ok.
