### ISSUE TITLE
'No license for swift' error after sonar-runner running 

### ISSUE THREAD

**Issue by hamsternik** [Backelite/sonar-swift#32]
Hi guys! I have a problem with running sonar-runner application (as you can see in topic of this issue). 

So, when i fire `run-sonar-script`, all steps before *sonar-runner* operate correctly. But after that line: `runCommand /dev/stdout sonar-runner`

I get next error:

>Running Lizard...Running SonarQube using SonarQube Runner.ERROR: Error during SonarQube Scanner execution 
ERROR: No license for swift
ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarQube Scanner with the -e switch.
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
ERROR - Command 'sonar-runner ' failed with error code: 1

Build process performs on my server using Jenkins (log was taken from Jenkins).

What does it means? As I understand, this *sonar-runner* is free, and all set of plugins, using by your plugin is free, too. So, what the *license* i need?

**Comment by giacgbj** [comment]
I'm quite sure you have installed a different plugin: http://www.sonarsource.com/products/plugins/languages/swift/ .
Look for the versions, for example.

**Comment by Dan-Andoni-BJSS** [comment]
I have the same problem. Will try re-downloading the plugin

**Comment by zippy1978** [comment]
Hi, 
Make sure that you have removed the commercial plugin from the plugin directory.

**Comment by hamsternik** [comment]
Thanx for all, problem was resolved by re-downloading & installing plugin 👯 .
