### ISSUE TITLE
Warnings instead of errors for unsupported SwiftLint rules

### ISSUE THREAD

**Issue by mgrebenets** [Backelite/sonar-swift#35]
Hi

We are facing an issue when the scanner fails when it sees "unknown" SwiftLint rule:

```
ERROR: Error during SonarQube Scanner execution
ERROR: The rule 'SwiftLint:legacy_cggeometry_functions' does not exist.
```

The thing is that `legacy_cggeometry_functions` is totally legit SwiftLint rule: https://github.com/realm/SwiftLint/search?utf8=%E2%9C%93&q=legacy_cggeometry_functions

Because the plugin doesn't support latest rules, the whole Sonar runner fails.

Could the plugin display a warning instead or even ignore the rules it does not support yet?

Otherwise, we are forced to use limited set of SwiftLint rules and forced to stay with older SwiftLint version, just because the plugin is not up to date. Or, for some reasons, we can't update the plugin on our CI server.

**Comment by zippy1978** [comment]
Hi,

Just fixed this issue (available on develop branch at the time).
