### ISSUE TITLE
Coverage report with relative paths are not supported

### ISSUE THREAD

**Issue by mgrebenets** [Backelite/sonar-swift#36]
Hi.

I used `fastlane`'s `slather` action to generate code coverage reports. The generation worked just fine. But since most of `fastlane` commands run in `.fastlane` directory, the report has relative paths, such as:

``` xml
  <sources>
    <source>/Users/myusername/path/to/project/.fastlane</source>
  </sources>
  <packages>
    <package name="...Sources" line-rate="0.1412300683371298" branch-rate="1.0000000000000000" complexity="0.0">
      <classes>
        <class name="MyClassName" filename="../Sources/MyClassName.swift" line-rate="0.9555555555555556" branch-rate="1.0000000000000000" complexity="0.0">
...
```

Note how `source` element path ends with `/.fastlane` and `filename` element starts with `../`.

However, `sonar-swift` plugin does not resolve these relative paths.

I don't mind using `slather`'s _output directory_ option to specify project directory as the output path and avoid relative paths issue, but it actually took me a lot of time experimenting and patching report file to figure out what is wrong.

It would definitely be helpful if `sonar-swift` could resolve such relative paths.

**Comment by mgrebenets** [comment]
Update: With further experimenting, I found out that the value of `<source>...` tag doesn't seem to matter. I changed `.fastlane` to `sonar-reports` and then I removed `.fastlane`. It all works good as long as I remove the `../` part from all paths.

Probably the sonar runner together with plugin look at `filename=` attribute only and expect it to be relative to current working directory.

**Comment by zippy1978** [comment]
Hi,
I managed to make Fastlane work.

Here is the documentation : https://github.com/Backelite/sonar-swift/blob/develop/docs/sonarqube-fastlane.md

Regards.

**Comment by zippy1978** [comment]
Could you tell me if it solved the issue for you ?
