### ISSUE TITLE
RFE - Linux support

### ISSUE THREAD

**Issue by slavonnet** [Backelite/sonar-swift#43]
Swift 3.0 now support linux Platform.
For simple code check XCode is overhead. 

Is you planned release for linux?

**Comment by pbernery** [comment]
We currently use this tool to check our iOS projects, so we use Xcode as the build tool.
We do not plan to add Linux support but any Pull Requests are welcome.

**Comment by zippy1978** [comment]
Hi @slavonnet,
There is a PR https://github.com/Backelite/sonar-swift/pull/51 we will merge soon that allows Swift analysis without XCode, it is using a Swift linter named 'tailor' (https://github.com/sleekbyte/tailor).

**Comment by zippy1978** [comment]
https://github.com/Backelite/sonar-swift/pull/51 is merged and available in version 0.3.1.
If you use Tailor as linter, it will run on Linux.
However, you will not be able to get all metrics without using xcodebuild.
