### ISSUE TITLE
How to define our own rules

### ISSUE THREAD

**Issue by jordirlatgit** [Backelite/sonar-swift#45]
We are looking for a way to validate that our developers are following our architecture design. So we want to have some rules to assure it. For example, some rules could be:

- We need to enforce all our custom viewControllers are instances of our (overloaded) BaseViewController, instead of ios Native UIViewController.

- We need to enforce all our custom Models (ListViewModel, for example)  obey some protocol ModelProtocol

- We need to enforce all our custom Models are following our naming conventions, let's say, al model classes name should end with "Model"

Is it possible to define these kind of rules? How should we start?
Is this plugin working with Swift 3?

**Comment by pbernery** [comment]
You should have a look at [SwiftLint](https://github.com/realm/SwiftLint) and its [custom rules feature](https://github.com/realm/SwiftLint#defining-custom-rules). 

sonar-swift does not enforce or check any rules as such. It gather results of many tools, such as SwiftLint, Slather, Lizard, ensure they are in a format compatible with SonarQube and push these to the Sonar server.

sonar-swift is not linked to any version of Swift. You just have to make sure your Xcode project is correctly set up.
