### ISSUE TITLE
brew install sonar-runner - `No available formula`

### ISSUE THREAD

**Issue by haemi** [Backelite/sonar-swift#46]
if  I try to install sonar-runner, I always get the following:

```
Error: No available formula with the name "sonar-runner"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

I also tried this here (http://macappstore.org/sonar-runner/) out, but no success either.

**Comment by MaikoHermans** [comment]
@haemi did you get this fixed? I'm having the same problem

**Comment by haemi** [comment]
I did, but unfortunately I don't know how any more... did you try `brew update`? Does `brew doctor` say something suspicious?

**Comment by MaikoHermans** [comment]
@haemi brew is up to date.
when I run `brew search sonar-runner` I do get 3 versions that can be installed.
when I run `brew doctor` I get one warning saying

> Xcode is installed to a directory with a space in the name.
> This will cause some formulae to fail to build.

**Comment by pbernery** [comment]
`sonar-runner` has been renamed `sonar-scanner`, that's why you cannot install it with `brew` anymore. 

`run-sonar-script.sh` still calls `sonar-runner`, so either you install it (manually, from the SonarQube web site) or you update your version of `run-sonar-script.sh` to call `sonar-scanner` instead of `sonar-runner`.

**Comment by MaikoHermans** [comment]
@pbernery 
as you probably noticed from my pull request I figured it out that the name changed.
Thanks for the answer tho!

**Comment by pbernery** [comment]
indeed 👍, I noticed afterwards.
