### ISSUE TITLE
quality gate pretty empty

### ISSUE THREAD

**Issue by haemi** [Backelite/sonar-swift#47]
I ran `run-sonar-swift.sh` in my project and it finishes successfully, the report looks pretty empty:
- no bugs
- no vulnerabilities
- no code smell
- no debt
- no duplications

as much as I would love to believe that, that's 100% impossible - 19k lines of code are scanned. Am I missing something?

My properties file looks like the following:

```
##########################
# Required configuration #
##########################

sonar.jacoco.reportMissing.force.zero=False

sonar.projectKey=...
sonar.projectName=...
sonar.projectVersion=1.0
# Comment if you have a project with mixed ObjC / Swift
sonar.language=swift

sonar.swift.workspace=....xcworkspace
sonar.swift.project=....xcodeproj

# Project description
sonar.projectDescription=...

# Path to source directories
sonar.sources=.
# Path to test directories (comment if no test)
# sonar.tests=TestDir

# Destination Simulator to run tests
# As string expected in destination argument of xcodebuild command
# Example = sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=9.2
sonar.swift.simulator=platform=iOS Simulator,name=iPhone 7,OS=10.1

# Xcode project configuration (.xcodeproj)
# and use the later to specify which project(s) to include in the analysis (comma separated list)
# Specify either xcodeproj or xcodeproj + xcworkspace
#sonar.swift.project=MyPrj.xcodeproj
#sonar.swift.workspace=MyWrkSpc.xcworkspace

# Scheme to build your application
sonar.swift.appScheme=Devel

# Configuration to use for your scheme. if you do not specify that the default will be Debug
#sonar.swift.appConfiguration=MyConfiguration

##########################
# Optional configuration #
##########################

# Encoding of the source code
sonar.sourceEncoding=UTF-8


# SCM
# sonar.scm.enabled=true
# sonar.scm.url=scm:git:http://xxx

# JUnit report generated by run-sonar.sh is stored in sonar-reports/TEST-report.xml
# Change it only if you generate the file on your own
# The XML files have to be prefixed by TEST- otherwise they are not processed
# sonar.junit.reportsPath=sonar-reports/

# Lizard report generated by run-sonar.sh is stored in sonar-reports/lizard-report.xml
# Change it only if you generate the file on your own
# sonar.swift.lizard.report=sonar-reports/lizard-report.xml

# Cobertura report generated by run-sonar.sh is stored in sonar-reports/coverage.xml
# Change it only if you generate the file on your own
# sonar.swift.coverage.reportPattern=sonar-reports/coverage*.xml

# OCLint report generated by run-sonar.sh is stored in sonar-reports/oclint.xml
# Change it only if you generate the file on your own
# sonar.swift.swiftlint.report=sonar-reports/*swiftlint.txt

# Paths to exclude from coverage report (tests, 3rd party libraries etc.)
# sonar.swift.excludedPathsFromCoverage=pattern1,pattern2
sonar.swift.excludedPathsFromCoverage=.*Tests.*

```

**Comment by pbernery** [comment]
Hello haemi,

You can check the content of the raw report files, in *&lt;your app folder&gt;/sonar-reports/*.
You may also try to use the `-v` option on `run-sonar-swift.sh`.

**Comment by haemi** [comment]
Hi pbernery,

thanks for your response?

In `sonar-reports/` I do have four files:

- coverage.xml
- lizard-report.xml
- TEST-report.xml
- xcodebuild.log

I got one step further, when changing the properties file:

```
sonar.language=swift
sonar.profile=SwiftLint
```

I now have values for code smells, but still no bugs or duplication, that's still missing.

**Comment by pbernery** [comment]
I see you don't have any SwiftLint reports generated (you should have `*-swiftlint.txt` files in the folder). SwiftLint is the tool that will report code smells and "bugs". 
I am not sure about duplication.

The execution of SwiftLint is tailored to the presence of folders in the `sonar.sources=` property. I see you set `sonar.sources=.` but in our projects we always specify a named folder. Try this, I believe specifying only . may not work with SwiftLint.

Example: if your project is called *Foo*, and you created the project with Xcode, you should have a folder *Foo* alongside the *Foo.xcodeproj* folder. Set `sonar.sources=Foo` in sonar-project.properties. You can more folder if needed: `sonar.sources=Foo,FooTests,FooUITests`

**Comment by grajan** [comment]
I am also stuck with the same issue. I changed the sources to my project name and still only code smells is being generated.

**Comment by Mindbowser** [comment]
Same issue at my end, any updates?

**Comment by Mindbowser** [comment]
I can see lizard-report and swiftlint under reports folder also I dont see Code Duplication results as well, its showing 0 all the time. Quick fix would be appreciated

**Comment by grajan** [comment]
@Mindbowser which version are you using?

**Comment by Mindbowser** [comment]
backelite-sonar-swift-plugin-0.3.4.jar is present on my sonar server.

**Comment by marius-bardan** [comment]
same here with sonar 6.3 and plugin 0.3.4. I can see duplications, but 0 bugs & vulnerabilities

**Comment by rafaelmaroxa** [comment]
Any updates on this? I still have the same issue.

**Comment by pbernery** [comment]
You are several reporting that the plugin seems to not work well with SonarQube 6.x.

I consider this ticket a duplicate of #90.
Feel free to reopen it if not.

**Comment by luowei428** [comment]
Hello, I run tests using:
SonarQube 6.5 & backelite-sonar-swift-plugin-0.3.5.jar.
And I can see that swiftlint finished. but there is no lint reports and 0 Bugs & Vulnerabilities.
Any suggestion would be appreciated.

Linting 'UserProfileController.swift' (41/42)
Linting 'Utils.swift' (42/42)
Done linting! Found 3680 violations, 751 serious in 42 files.

**Comment by USHASHENDRE** [comment]
Ya, i am also getting same problem when iam running 2nd time using jenkins... I am getting 0(Zero) for Bugs, Vulnerabilities, codesmells and Debt... and 15.9% of Duplications and 9.4K of Dulicated Blocks...
for sonarqube 5.6.7  anybody having  solutions then please comment it

**Comment by sagarmore62** [comment]
facing same issue @USHASHENDRE . Did you find any work around?
