### ISSUE TITLE
Not getting any records and/or language not getting recognized

### ISSUE THREAD

**Issue by aleixo** [Backelite/sonar-swift#49]
Hi

I have everything installed and run the script sucessfully runs and start the server. Dispite that, i have no bugs or other issues on my project (strange).

And if i set the language to swift, it will throw an error like the one on the image

<img width="795" alt="screen shot 2016-11-10 at 00 52 37" src="https://cloud.githubusercontent.com/assets/4128120/20160595/1877a970-a6e0-11e6-9caa-586a504ae961.png">

Also my properties is the one that follows

##########################
# Required configuration #
##########################

sonar.projectKey=myADAURAmeds
sonar.projectName=myADAURAmeds
sonar.projectVersion=1.0.29
sonar.language=swift
sonar.profile=SwiftLint

sonar.projectDescription=ADAURA
sonar.sources=/Users/altran/Documents/ADAURA/myADAURAmeds/myADAURAmeds
#sonar.tests=/Users/altran/Documents/ADAURA/myADAURAmeds/myADAURAmedsTests

sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=10.1
sonar.swift.project=myADAURAmeds.xcodeproj
sonar.swift.workspace=myADAURAmeds.xcworkspace
sonar.swift.appScheme=myADAURAmeds
sonar.swift.testScheme=myADAURAmedsTests

sonar.sourceEncoding=UTF-8
sonar.swift.excludedPathsFromCoverage=.*Tests.*

--------------

I tried to find the language directive on .sh file but seems to have none. My xCode is version 8. Thank you very much.

**Comment by pbernery** [comment]
Hey aleixo. Apparently you do not have the SonarQube plugin installed. It declares the Swift language. Ensure it is correctly installed and that you use a compatible SonarQube server version.

**Comment by geoDDB** [comment]
@aleixo 
 Hi, same problem here  with error "You must install a plugin that supports the language 'swift'".
Do you find a solution?

**Comment by pbernery** [comment]
SonarQube may be installed, but you also have to install the Sonar Swift plugin into your SonarQube instance (see [documentation](https://github.com/Backelite/sonar-swift#installation-once-for-all-your-swift-projects)).
