### ISSUE TITLE
ERROR: Caused by: The rule 'SwiftLint:legacy_constant' does not exist.

### ISSUE THREAD

**Issue by akshaysyaduvanshi** [Backelite/sonar-swift#5]
Ran the script run-sonar-swift.sh and it is giving the above error in command sonar-runner.

Running SonarQube using SonarQube Runner.................................ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: The rule 'SwiftLint:legacy_constant' does not exist.
ERROR:
ERROR: To see the full stack trace of the errors, re-run SonarQube Runner with the -e switch.
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
ERROR - Command 'sonar-runner ' failed with error code: 1

**Comment by akshaysyaduvanshi** [comment]
This error was occurring because i was using higher version of swiftlint.

**Comment by zippy1978** [comment]
Yes.
I need to issue a new release with news SwiftLint version support... However Swiftlint 0.7 broke their "rules" output and I cannot integrate it at the moment.
