### ISSUE TITLE
Confused what to do with installation instruction

### ISSUE THREAD

**Issue by MaikoHermans** [Backelite/sonar-swift#52]
I'm trying to get this to work on a linux server however I'm stuck right here

Copy run-sonar-swift.sh somewhere in your PATH
Restart the SonarQube server.

What am I supposed to do with the script exactly? Should it just be created anywhere on my server. For instance in my home directory or does this imply something special needs to be done with it.

Hope you can help me out

**Comment by pbernery** [comment]
Hey Maiko,

As mentioned in [Launching an analysis](https://github.com/Backelite/sonar-swift#launching-an-analysis) in the README, execute `run-sonar-script.sh` in the root of your Xcode project to launch every analysis tools and push results to the SonarQube server with sonar-runner.

Putting the file in your PATH is a convenience but you can put it were you want.

**Comment by MaikoHermans** [comment]
@pbernery 
Understood. I got it to run however it throws an error.

What I'm doing is the following
I have jenkins and sonarqube running on a ubuntu server.
I have a mac build server. 

I installed all the required extensions on the mac build server.
the jar is installed in the sonar extension directory.

The sonar-project.properties looks as follows
`##########################
# Required configuration #
##########################

sonar.projectKey=prjKey
sonar.projectName=prjName
sonar.projectVersion=1.0
# Comment if you have a project with mixed ObjC / Swift
sonar.language=swift

# Project description
sonar.projectDescription=prjDescription

# Path to source directories
sonar.sources=ttt
# Path to test directories (comment if no test)
sonar.tests=tttTests

# Destination Simulator to run tests
# As string expected in destination argument of xcodebuild command
# Example = sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=9.2
sonar.swift.simulator=platform=iOS Simulator,id=FEF05FDC-56BD-48B9-BDFD-210CCFF5BC37

# Xcode project configuration (.xcodeproj)
# and use the later to specify which project(s) to include in the analysis (comma separated list)
# Specify either xcodeproj or xcodeproj + xcworkspace
sonar.swift.project=ttt.xcodeproj
sonar.swift.workspace=ttt.xcworkspace

# Scheme to build your application
sonar.swift.appScheme=tttTests

# Configuration to use for your scheme. if you do not specify that the default will be Debug
sonar.swift.appConfiguration=Debug

##########################
# Optional configuration #
##########################

# Encoding of the source code
sonar.sourceEncoding=UTF-8


# SCM
# sonar.scm.enabled=true
# sonar.scm.url=scm:git:http://xxx

# JUnit report generated by run-sonar.sh is stored in sonar-reports/TEST-report.xml
# Change it only if you generate the file on your own
# The XML files have to be prefixed by TEST- otherwise they are not processed
# sonar.junit.reportsPath=sonar-reports/

# Lizard report generated by run-sonar.sh is stored in sonar-reports/lizard-report.xml
# Change it only if you generate the file on your own
# sonar.swift.lizard.report=sonar-reports/lizard-report.xml

# Cobertura report generated by run-sonar.sh is stored in sonar-reports/coverage.xml
# Change it only if you generate the file on your own
# sonar.swift.coverage.reportPattern=sonar-reports/coverage*.xml

# OCLint report generated by run-sonar.sh is stored in sonar-reports/oclint.xml
# Change it only if you generate the file on your own
# sonar.swift.swiftlint.report=sonar-reports/*swiftlint.txt

# Paths to exclude from coverage report (tests, 3rd party libraries etc.)
# sonar.swift.excludedPathsFromCoverage=pattern1,pattern2
sonar.swift.excludedPathsFromCoverage=.*Tests.*
`

however I get the following error in jenkins. 
`.Running tests..............................2016-11-29 22:45:31.155 xcodebuild[46152:893312] [MT] IDETestOperationsObserverDebug: (518E1A41-0024-4CBA-8DBE-6C6B6D2F415B) Beginning test session tttTests-518E1A41-0024-4CBA-8DBE-6C6B6D2F415B at 2016-11-29 22:45:31.149 with Xcode 8B62 on target <DVTiPhoneSimulator: 0x7febd3391a50> {
		SimDevice: SimDevice : iPhone 7 (FEF05FDC-56BD-48B9-BDFD-210CCFF5BC37) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-7 } runtime={ SimRuntime : 10.1 (14B72) - com.apple.CoreSimulator.SimRuntime.iOS-10-1 }
} (10.1 (14B72))
2016-11-29 22:45:31.155 xcodebuild[46152:893489]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/maiko/Library/Developer/Xcode/DerivedData/ttt-bynjkkucgsycxpacfgqjqrjyspbx/Logs/Test/A40A4B3F-3BE8-491D-939D-51908C3FEECC/Session-tttTests-2016-11-29_224531-0Gph6U.log
................................
[!] /Users/maiko/build/workspace/lbp-iOS/Pods/Alamofire/Source/Request.swift:474:47: expression implicitly coerced from 'URLSessionTask?' to Any

            userInfo: [Notification.Key.Task: task]
                                              ^~~~


[!] /Users/maiko/build/workspace/lbp-iOS/Pods/PusherSwift/Source/PusherConnection.swift:526:50: 'requestFor(socketID:channel:)' is deprecated: use requestFor(socketID: String, channelName: String) -> URLRequest? instead

                        if let request = builder.requestFor?(socketID: socketID, channel: channel) {
                                              ^~~~

/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:422:in `===': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:422:in `update_test_state'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:299:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/printer.rb:19:in `pretty_print'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/bin/xcpretty:84:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/bin/xcpretty:83:in `each_line'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/bin/xcpretty:83:in `<top (required)>'
	from /usr/local/bin/xcpretty:22:in `load'
	from /usr/local/bin/xcpretty:22:in `<main>'
mv: build/reports/junit.xml: No such file or directory
Computing coverage report./usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/project.rb:459:in `find_binary_files': No product binary found in /Users/maiko/Library/Developer/Xcode/DerivedData/ttt-bynjkkucgsycxpacfgqjqrjyspbx/Build/Intermediates/CodeCoverage. (StandardError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/project.rb:344:in `configure_binary_file'
	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/project.rb:240:in `configure'
	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:51:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:22:in `load'
	from /usr/local/bin/slather:22:in `<main>'
ERROR - Command 'slather coverage --input-format profdata -i .*Tests.* --cobertura-xml --output-directory sonar-reports --workspace ttt.xcworkspace --scheme tttTests ttt.xcodeproj' failed with error code: 1
Build step 'Execute shell' marked build as failure
Recording test results`

Could it be that I'm either doing something wrong or that it can't work the way I have set it up?

**Comment by pbernery** [comment]
Well, the log states that xcpretty is failing. xcpretty is used to translate Xcode log in another format (in our case, JUnit test results).

Looking for the error of xcpretty ("invalid byte sequence in US-ASCII"), I found this issue https://github.com/supermarin/xcpretty/issues/48. You environment must be configured to accept UTF-8 characters.

**Comment by MaikoHermans** [comment]
@pbernery 
I executed `export LC_ALL="en_US.UTF-8"`
when I run `locale` I get the following output

LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

However I still get the same error. I can't seem to figure out what's causing it or how to fix it.
