### ISSUE TITLE
code coverage not showing

### ISSUE THREAD

**Issue by MaikoHermans** [Backelite/sonar-swift#57]
I've managed to run everything like it should.
When I look at the coverage report it looks as follows.

> <?xml version="1.0"?>
> <!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
> <coverage line-rate="1.0000000000000000" branch-rate="1.0000000000000000" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="0.0" timestamp="1480615673" version="Slather 2.3.0">
>   <sources>
>     <source>/my/buildpath/build/workspace/lbp-iOS</source>
>   </sources>
>   <packages/>
> </coverage>

Which is located in the sonar-reports directory

However when I look in sonarqube itself it doesn't show me the code coverage at all.
<img width="469" alt="screen shot 2016-12-01 at 19 24 13" src="https://cloud.githubusercontent.com/assets/6593958/20806598/e00657da-b7fb-11e6-80dd-81c47bd7c25e.png">

Looking at jenkins this is the log.

> .Running tests...........................2016-12-01 19:05:23.186 xcodebuild[67612:387050] [MT] IDETestOperationsObserverDebug: (12236375-272E-4805-83C1-F189C886B87D) Beginning test session tttTests-12236375-272E-4805-83C1-F189C886B87D at 2016-12-01 19:05:23.178 with Xcode 8B62 on target <DVTiPhoneSimulator: 0x7f962e5dacf0> {
> 		SimDevice: SimDevice : iPhone 7 (FEF05FDC-56BD-48B9-BDFD-210CCFF5BC37) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-7 } runtime={ SimRuntime : 10.1 (14B72) - com.apple.CoreSimulator.SimRuntime.iOS-10-1 }
> } (10.1 (14B72))
> 2016-12-01 19:05:23.191 xcodebuild[67612:387230]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> /Users/maiko/Library/Developer/Xcode/DerivedData/ttt-bynjkkucgsycxpacfgqjqrjyspbx/Logs/Test/9575296F-7EBF-4B1E-91F4-B3C28069EC07/Session-tttTests-2016-12-01_190523-ToW5eV.log
> ............................
> .
> ⚠️  /Users/maiko/build/workspace/lbp-iOS/Pods/Alamofire/Source/Request.swift:474:47: expression implicitly coerced from 'URLSessionTask?' to Any
> 
>             userInfo: [Notification.Key.Task: task]
>                                               ^~~~
> 
> 
> ⚠️  /Users/maiko/build/workspace/lbp-iOS/Pods/PusherSwift/Source/PusherConnection.swift:526:50: 'requestFor(socketID:channel:)' is deprecated: use requestFor(socketID: String, channelName: String) -> URLRequest? instead
> 
>                         if let request = builder.requestFor?(socketID: socketID, channel: channel) {
>                                               ^~~~
> 
> 
> ⚠️  /Users/maiko/build/workspace/lbp-iOS/Pods/PusherSwift/Source/PusherConnection.swift:526:50: 'requestFor(socketID:channel:)' is deprecated: use requestFor(socketID: String, channelName: String) -> URLRequest? instead
> 
>                         if let request = builder.requestFor?(socketID: socketID, channel: channel) {
>                                                  ^
> 
> 
> ⚠️  /Users/maiko/build/workspace/lbp-iOS/Pods/Alamofire/Source/Request.swift:474:47: expression implicitly coerced from 'URLSessionTask?' to Any
> 
>             userInfo: [Notification.Key.Task: task]
>                                                  ^
> 
> .
> 
> Executed 1 test, with 0 failures (0 unexpected) in 0.005 (0.009) secondsComputing coverage report.[0;31merror: Failed to load coverage: Is a directory[0m
> 
> Running SwiftLint...Linting Swift files at path ttt
> Linting '_Result.swift' (1/28)
> Linting 'AppDelegate.swift' (2/28)
> Linting 'Array+Random.swift' (3/28)
> Linting 'Duration.swift' (4/28)
> Linting 'FinalCollectionViewCell.swift' (5/28)
> Linting 'Game.swift' (6/28)
> Linting 'GenerateQRController.swift' (7/28)
> Linting 'IntroCollectionViewCell.swift' (8/28)
> Linting 'IntroductionView.swift' (9/28)
> Linting 'IntroViewController.swift' (10/28)
> Linting 'JoinGameController.swift' (11/28)
> Linting 'Network.swift' (12/28)
> Linting 'NetworkError.swift' (13/28)
> Linting 'NewGameIntroViewController.swift' (14/28)
> Linting 'Page.swift' (15/28)
> Linting 'Player.swift' (16/28)
> Linting 'PusherSwift+Extension.swift' (17/28)
> Linting 'Score.swift' (18/28)
> Linting 'ScoreTableViewController.swift' (19/28)
> Linting 'Session.swift' (20/28)
> Linting 'SessionPlayerTableController.swift' (21/28)
> Linting 'StartscreenTextField.swift' (22/28)
> Linting 'StartViewController.swift' (23/28)
> Linting 'Status.swift' (24/28)
> Linting 'String+Extensions.swift' (25/28)
> Linting 'Target.swift' (26/28)
> Linting 'UIAlertController+Extension.swift' (27/28)
> Linting 'UIViewController+Extension.swift' (28/28)
> Done linting! Found 205 violations, 4 serious in 28 files.
> Running Lizard...Running SonarQube using SonarQube Runner.....WARN: The rule 'SwiftLint:vertical_whitespace' does not exist.
> WARN: The rule 'SwiftLint:vertical_whitespace' does not exist.
> WARN: The rule 'SwiftLint:vertical_whitespace' does not exist.
> WARN: The rule 'SwiftLint:vertical_whitespace' does not exist.
> WARN: The rule 'SwiftLint:vertical_whitespace' does not exist.
> .
> Recording test results

**I notice this line in the log**
> Executed 1 test, with 0 failures (0 unexpected) in 0.005 (0.009) secondsComputing coverage report.[0;31merror: Failed to load coverage: Is a directory[0m

**I'm not sure if it is a problem with my properties file that looks like this.**

> ##########################
> #Required configuration#
> ##########################
> 
> sonar.projectKey=ttt
> sonar.projectName=RunForestRun
> sonar.projectVersion=1.0
> #Comment if you have a project with mixed ObjC / Swift
> sonar.language=swift
> 
> #Project description
> sonar.projectDescription=Run Forest Run application
> 
> #Path to source directories
> sonar.sources=ttt
> #Path to test directories (comment if no test)
> sonar.tests=tttTests
> 
> #Destination Simulator to run tests
> #As string expected in destination argument of xcodebuild command
> #Example = sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=9.2
> sonar.swift.simulator=platform=iOS Simulator,id=FEF05FDC-56BD-48B9-BDFD-210CCFF5BC37
> 
> #Xcode project configuration (.xcodeproj)
> #and use the later to specify which project(s) to include in the analysis (comma separated list)
> #Specify either xcodeproj or xcodeproj + xcworkspace
> sonar.swift.project=ttt.xcodeproj
> sonar.swift.workspace=ttt.xcworkspace
> 
> #Scheme to build your application
> sonar.swift.appScheme=ttt
> 
> #Configuration to use for your scheme. if you do not specify that the default will be Debug
> sonar.swift.appConfiguration=Debug
> 
> ##########################
> #Optional configuration#
> ##########################
> 
> #Encoding of the source code
> sonar.sourceEncoding=UTF-8
> 
> 
> #SCM
> #sonar.scm.enabled=true
> #sonar.scm.url=scm:git:http://xxx
> 
> #JUnit report generated by run-sonar.sh is stored in sonar-reports/TEST-report.xml
> #Change it only if you generate the file on your own
> #The XML files have to be prefixed by TEST- otherwise they are not processed
> #sonar.junit.reportsPath=sonar-reports/
> 
> #Lizard report generated by run-sonar.sh is stored in sonar-reports/lizard-report.xml
> #Change it only if you generate the file on your own
> #sonar.swift.lizard.report=sonar-reports/lizard-report.xml
> 
> #Cobertura report generated by run-sonar.sh is stored in sonar-reports/coverage.xml
> #Change it only if you generate the file on your own
> #sonar.swift.coverage.reportPattern=sonar-reports/coverage*.xml
> 
> #OCLint report generated by run-sonar.sh is stored in sonar-reports/oclint.xml
> #Change it only if you generate the file on your own
> #sonar.swift.swiftlint.report=sonar-reports/*swiftlint.txt
> 
> #Paths to exclude from coverage report (tests, 3rd party libraries etc.)
> #sonar.swift.excludedPathsFromCoverage=pattern1,pattern2
> sonar.swift.excludedPathsFromCoverage=.*Tests.*

**Comment by zippy1978** [comment]
@MaikoHermans,

This is pretty strange, I cannot spot the "Failed to load coverage" log in the plugin code...
Is that an issue with Xcode 8.1 ?

Could you show me the coverage.xml file generated inside the sonar-reports folder ?

Gilles

**Comment by MaikoHermans** [comment]
@zippy1978 
I thought it was strange as well. I couldn't find the "Failed to load coverage" anywhere either.

So I did some more digging and figured it must come from slather. I changed the script a little in the way it prints to the log and to try to get the slather command running with `--verbose` so I could see what happened. It doesn't print the verbose to the log I guess since this is what I'm getting now.

> Executed 1 test, with 0 failures (0 unexpected) in 0.007 (0.011) seconds
> Computing coverage report
> slather coverage --verbose --input-format profdata --cobertura-xml --output-directory sonar-reports --workspace ttt.xcworkspace --scheme ttt --binary-file ttt ttt.xcodeproj
> [0;31merror: Failed to load coverage: Is a directory[0m

atleast it makes it clear that something goes wrong in the slather command and that's where the "failed to load coverage" line comes from.

As for my coverage.xml file.

> <?xml version="1.0"?>
> <!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
> <coverage line-rate="1.0000000000000000" branch-rate="1.0000000000000000" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="0.0" timestamp="1480663838" version="Slather 2.3.0">
>   <sources>
>     <source>/Users/myuser/build/workspace/lbp-iOS</source>
>   </sources>
>   <packages/>
> </coverage>

**Comment by MaikoHermans** [comment]
Alright I figured it out.

What happened was that the --binary-file caused an error.
What I ended up doing is changing --binary-file to --binary-basename.

Which fixed it completely. 
I'll create a new PR with things changed so it should work
