### ISSUE TITLE
skip slather

### ISSUE THREAD

**Issue by croccio** [Backelite/sonar-swift#65]
is it possible skip slather?

**Comment by pbernery** [comment]
run-sonar-swift.sh could be updated for this. 

A parameter could be added here (like -nocoverage): https://github.com/Backelite/sonar-swift/blob/fd751839c1c92bb34c27d6b2fde252c0e802772e/src/main/shell/run-sonar-swift.sh#L142

Then code should be updated from here to use this parameter: https://github.com/Backelite/sonar-swift/blob/fd751839c1c92bb34c27d6b2fde252c0e802772e/src/main/shell/run-sonar-swift.sh#L298
