### ISSUE TITLE
Take into account .swiftlint.yml

### ISSUE THREAD

**Issue by oleghnidets** [Backelite/sonar-swift#66]
Hi,

When I have `.swiftlint.yml` into my root directory and execute `sh run-swift-sonar.sh` I get zero issue on Dashboard. I know that I can customize rules but if I launch `swiftlint autocorrect` Pods folder is included. If you can, please, fix this.

Thank you in advance

**Comment by nikhilsh** [comment]
@oleghnidets Hey there, I think I'm encountering the same issue as you. I have a `.swiftlint.yml` file locally that I use to exclude `Pods` and to modify some rules. I've been searching on the sonar UI for a while but I can't seem to find a way to configure the rules? 

I'd love it if `swiftlint.yml` were to work, but barring that, could I please check with you how to configure the rules for swiftlint, for example this rule in `.swiftlint.yml`:   
```identifier_name:
min_length: # only min_length
error: 4 # only error
excluded: # excluded via string array
 - id
 - ID
 - URL
```

**Comment by auryn31** [comment]
Have the same problem here, 
can configure and disable rules above the .yml file
but cannot import custom rules to sonarqube
-> get the error WARN: The rule 'SwiftLint:curly_brackets' does not exist.
-> get no of my own rules shown at the dashboard, all other rules works fine

**Comment by zippy1978** [comment]
Hi,
When using the plugin, you cannot control the rules (and add custom rules) with .swiftlint.yml.
You must do it the Sonar way by creating a custom quality profile and apply this profile to your project.

Gilles

**Comment by Benuuu** [comment]
@zippy1978 why is it this way? We have SonarQube set up to run against many projects, some projects would like to develop their own .swiftlint.yml file.  It doesn't make sense for us to have to duplicate the rules in both places for this.

**Comment by andrewclaus** [comment]
This should, and can, be a thing. I am not sure how hard it is to connect up the .yml configuration file, but the kotlin "detekt" plugin is able to load this file from each individual project as shown by the sonarqube settings: 
![screen shot 2018-08-08 at 4 54 18 pm](https://user-images.githubusercontent.com/26550989/43864224-2211c63a-9b2d-11e8-8642-bd42caa50d0d.png)

**Comment by andrewclaus** [comment]
Found the commit where this was added to detekt! https://github.com/arturbosch/detekt/commit/4e2f74721e3b8ced15f83f0a0a93af837ef1b4d9
