### ISSUE TITLE
sonar-swift doesn't support sonarqube v6.2

### ISSUE THREAD

**Issue by ssheru** [Backelite/sonar-swift#68]
We have been using open source Swift plugin for Sonarqube 5.6 and we recently upgraded to Sonarqube v6.2 and indeed this plugin is unsupported.

Can you please update these plugin to support Sonarqube v6.2.

Any help is highly appreciated.

**Comment by zippy1978** [comment]
Hi, 

This is a duplicate of https://github.com/Backelite/sonar-swift/issues/61

**Comment by ssheru** [comment]
Thanks Zippy1978...
