### ISSUE TITLE
Unable to successfully run sonar analyzer

### ISSUE THREAD

**Issue by oleandre** [Backelite/sonar-swift#69]
Hello! I'm unable to successfully run an analysis for my Swift project. 

MY SONAR-PROJECT.PROPERTIES file(Look further down for the error message I get)
##########################
# Required configuration #
##########################

# Project key will also be used for binary file 
sonar.projectKey=viten-i-senter-ios
sonar.projectName=viten-i-senter-ios
sonar.projectVersion=1.0
# Comment if you have a project with mixed ObjC / Swift
sonar.language=swift

# Project description
sonar.projectDescription=App for vitensenteret innlandet

# Path to source directories
sonar.sources=./viten-i-senter-ios
# Path to test directories (comment if no test)
# sonar.tests=TestDir

# Destination Simulator to run tests
# As string expected in destination argument of xcodebuild command
# Example = sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=9.2
sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=9.2

# Xcode project configuration (.xcodeproj)
# and use the later to specify which project(s) to include in the analysis (comma separated list)
# Specify either xcodeproj or xcodeproj + xcworkspace
sonar.swift.project=viten-i-senter-ios.xcodeproj
sonar.swift.workspace=viten-i-senter-ios.xcworkspace

# Specify your appname.
# This will be something like "myApp"
# Use when basename is different from targeted scheme. 
# Or when slather fails with 'No product binary found'
# sonar.swift.appName=viten-i-senter-ios

# Scheme to build your application
sonar.swift.appScheme=viten-i-senter-ios

# Configuration to use for your scheme. if you do not specify that the default will be Debug
sonar.swift.appConfiguration=Debug

##########################
# Optional configuration #
##########################

# Encoding of the source code
#sonar.sourceEncoding=UTF-8

# SCM
# sonar.scm.enabled=true
# sonar.scm.url=scm:git:http://xxx

# JUnit report generated by run-sonar.sh is stored in sonar-reports/TEST-report.xml
# Change it only if you generate the file on your own
# The XML files have to be prefixed by TEST- otherwise they are not processed
# sonar.junit.reportsPath=sonar-reports/

# Lizard report generated by run-sonar.sh is stored in sonar-reports/lizard-report.xml
# Change it only if you generate the file on your own
# sonar.swift.lizard.report=sonar-reports/lizard-report.xml

# Cobertura report generated by run-sonar.sh is stored in sonar-reports/coverage.xml
# Change it only if you generate the file on your own
# sonar.swift.coverage.reportPattern=sonar-reports/coverage*.xml

# OCLint report generated by run-sonar.sh is stored in sonar-reports/oclint.xml
# Change it only if you generate the file on your own
# sonar.swift.swiftlint.report=sonar-reports/*swiftlint.txt

# Change it only if you generate the file on your own
# sonar.swift.tailor.report=sonar-reports/*tailor.txt

# Paths to exclude from coverage report (tests, 3rd party libraries etc.)
# sonar.swift.excludedPathsFromCoverage=pattern1,pattern2
sonar.swift.excludedPathsFromCoverage=.*Tests.*

##########################
# Tailor configuration #
##########################
# Tailor configuration
# -l,--max-line-length=<0-999>                  maximum Line length (in characters)
#    --list-files                               display Swift source files to be analyzed
#    --max-class-length=<0-999>                 maximum Class length (in lines)
#    --max-closure-length=<0-999>               maximum Closure length (in lines)
#    --max-file-length=<0-999>                  maximum File length (in lines)
#    --max-function-length=<0-999>              maximum Function length (in lines)
#    --max-name-length=<0-999>                  maximum Identifier name length (in characters)
#    --max-severity=<error|warning (default)>   maximum severity
#    --max-struct-length=<0-999>                maximum Struct length (in lines)
#    --min-name-length=<1-999>                  minimum Identifier name length (in characters)
sonar.swift.tailor.config=--max-line-length=100 --max-file-length=500 --max-name-length=40 --max-name-length=40 --min-name-length=4

ERROR MESSAGE I GET WHEN RUNNING run-sonar-swift.sh

Running run-sonar-swift.sh...
.rm: sonar-reports/coverage.xml: Permission denied
rm: sonar-reports/TEST-report.xml: Permission denied
rm: sonar-reports/xcodebuild.log: Permission denied
rm: sonar-reports: Directory not empty
mkdir: sonar-reports: File exists
./run-sonar-swift.sh: line 256: sonar-reports/TEST-report.xml: Permission denied
./run-sonar-swift.sh: line 257: sonar-reports/coverage.xml: Permission denied
Running tests./run-sonar-swift.sh: line 108: sonar-reports/xcodebuild.log: Permission denied
ERROR - Command 'xcodebuild clean build test -workspace viten-i-senter-ios.xcworkspace -scheme viten-i-senter-ios -configuration Debug -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone 6,OS=9.2 -destination-timeout 60' failed with error code: 1

**Comment by jasminpethani** [comment]
you should try running following command which gives you more explanation of what's the acual error is:

xcodebuild clean build test -workspace viten-i-senter-ios.xcworkspace -scheme viten-i-senter-ios -configuration Debug -enableCodeCoverage YES -destination platform=iOS Simulator,name=iPhone 6,OS=9.2

**Comment by zippy1978** [comment]
Hi,

It seems your iOS Simulator is not launching.
Is an iPhone 6 / OS 9.2 a simulator that exists in Xcode ?

**Comment by zippy1978** [comment]
Issue too old. Closing.
