### ISSUE TITLE
Sonar showing ignored folders 

### ISSUE THREAD

**Issue by abhishekgoyal12** [Backelite/sonar-swift#70]
Hi,

We are using sonarqube 5.6.4 and backelite plugin version 0.2.3.

When jenkins pushing lizard xml to sonar then its showing errors in the files which were set ignored in .yml file.

Please help.

**Comment by pbernery** [comment]
This is maybe a bug from Lizard, or maybe you need to exclude. those files in the sonar-project.properties file as well. See [sonar-project.properties](https://github.com/Backelite/sonar-swift/blob/develop/sonar-project.properties#L78).
