### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by senty** [Backelite/sonar-swift#71]
Hi guys,

is this plugin supporting Swift 3 ?

Thank you very much !

**Comment by salmojunior** [comment]
Hi senty,

I tested in my project with Swift 3.1 and it worked great.

**Comment by pbernery** [comment]
Indeed. As far as I know, sonar-swift is not dependent on the Swift version. sonar-swift only runs reporting tools and aggregates the report into SonarQube. 
The reporting tools are responsible of the support of new language version or features. In our case, SwiftLint, Lizard and optionally Taylor.
