### ISSUE TITLE
sonar-project.properties not work for fastlane.

### ISSUE THREAD

**Issue by wangjiejacques** [Backelite/sonar-swift#76]
I add
```
sonar.junit.reportsPath=reports/
sonar.junit.include=*.junit
sonar.swift.lizard.report=reports/lizard-report.xml
sonar.swift.coverage.reportPattern=reports/cobertura.xml
sonar.swift.swiftlint.report=reports/*swiftlint.txt
```
in sonar-project.properties, and the sonarqube doesn't work, all the measures is 0, and If I remove the above configurations, run `fastlane metrics` , I can get some measures.

**Comment by Piramanayagamm** [comment]
Any update on this?

**Comment by singh88** [comment]
Another possible solution could be to use [fastlane sonar actions](https://docs.fastlane.tools/actions/sonar/). If we use this configuration then we can get rid of this extra file.

**Comment by nfalco79** [comment]
the reason maybe is that the sonar.junit.reportsPath is wrong

the correct one is [sonar.swift.surefire.junit.reportsPath](https://github.com/Backelite/sonar-swift/blob/1066361e737570febd4c09ce889045c6f2def800/sonar-swift-plugin/src/main/java/com/backelite/sonarqube/swift/surefire/SurefireSensor.java#L36)

**Comment by gaelfoppolo** [comment]
Does @nfalco79 answer solves your issue?

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
