### ISSUE TITLE
WARN: The rule 'SwiftLint:curly_brackets' does not exist.

### ISSUE THREAD

**Issue by auryn31** [Backelite/sonar-swift#89]
Dear All,
I try to include custom rules into sonarqube.
So I write the rules into an custom .swiftlint.yml file and referenced this in the run-sonar-swift.sh script.
Now I get the Warning:
WARN: The rule 'SwiftLint:curly_brackets' does not exist.
And did not see the errors/warnings in sonarqube from my own profile.
How did I get the custom rules shown in sonarqube?
Thanks a lot for help.

**Comment by zippy1978** [comment]
Hi,
You cannot actually use custom rules with SonarQube, because all issues must be bundled with the plugin (each issue must have a severity and fix time estimation assigned to it).

Gilles
