### ISSUE TITLE
Can we create custom rules/percentages for rules

### ISSUE THREAD

**Issue by MaikoHermans** [Backelite/sonar-swift#92]
So we are currently setting up a new rules within the company like:

- file length

By default the file length rule is to be less then about 400 lines of code

However we want to set our own values for these rules. can we do this someway in sonarqube? if so how can this be achieved?

**Comment by pbernery** [comment]
Check the SonarQube documentation for that, or maybe SwiftLint if you delegate this rule to it.
sonar-swift only runs the tools and aggregates the reports from these. They must be configured by yourself depending on your project.

I close this ticket as this is probably not related to sonar-swift. Feel free to reopen it if I am mistaken.
