### ISSUE TITLE
Instructions to work with remote SonarQube and bitbucket

### ISSUE THREAD

**Issue by Mindbowser** [Backelite/sonar-swift#93]
We have existing SonarQube hosted on AWS and using bitbucket to analyze code for other technologies, whenever someone commits the code bitbucket pipeline gets executed and reports are sent to SonarQube. Can we have updated documentation for same?

**Comment by pbernery** [comment]
I don't believe this is related to sonar-swift plugi, but more to SonarQube itself, isn't it?

**Comment by oookotooo** [comment]
Hello,

I  have same problem. I have installed SonarQube, Installed swift plugin. Using jenkins it triggers to check code every commit.

SonarQube works fine with python. It shows issues, etc.
But with swift it shows 100% everything perfect. No issues, no problems. It seems like it is not working at all. 

running run-sonar-swift.sh is only for localy installed sonarqube. How can I use it with remote-installed sonarqube?

**Comment by zippy1978** [comment]
Hi @oookotooo,

What do you mean by "running run-sonar-swift.sh is only for localy installed sonarqube" ?
run-sonar-swift.sh is the script used to trigger the analysis, it uses sonar-scanner to send data to the remote server.

**Comment by oookotooo** [comment]
Hi @zippy1978,

I said that because, if you want to check your code using sonar-swift, you need mac, and you need to run `run-sonar-swift.sh` script locally, and only after that you can see results of checks in sonarQube (remote or local).

What I want is just check a swift code on my linux server just using sonarQube. It would be great if it would be possible.

**Comment by gaelfoppolo** [comment]
Is this issue still valid?
Without any response, I will close it.

**Comment by gaelfoppolo** [comment]
Closing this issue. Please open a new one if you're experiencing this.
