### ISSUE TITLE
WARN: file for test class not found

### ISSUE THREAD

**Issue by anandfnc** [Backelite/sonar-swift#99]
I had setup sonarqube with Swift plugin for my project(mix of Objective-C and Swift). I am getting lot of "test class not found" warnings. It look likes that this warning is shown only for Objective-C test classes and not for Swift test class. 

INFO: parsing sonar-reports
WARN: file for test class <TestClassName> not found

Also, I just see Swift unit test cases count alone is shown in SonarQube dashboard. I don't get total count (inclusive of Objective-C)  in dashboard. Is that bcos of this warning?

**Comment by pbernery** [comment]
sonar-swift does not work quite well yet with mixed Obj-C/Swift project.
sonar-swift only reports info for Swift files.

**Comment by anandfnc** [comment]
is it possible to have both Obj-C and Swift plugin in mixed project ? will that solve these problems? I want see both Obj-C and Swift files and test classes in my Dashboard.

**Comment by zippy1978** [comment]
Hi @anandfnc,

We are currently talking about it (mixing ObjC and Swift in a single plugin)....

**Comment by anandfnc** [comment]
Thanks @zippy1978 and @pbernery

**Comment by gaelfoppolo** [comment]
Do you still face this issue @anandfnc, with the current version of the plugin, now that it supports both Swift and Objective-C?

**Comment by davidy4ng** [comment]
Old issue, i'm closing.
